---
permalink: sg6000/installation-and-deployment-overview.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, Installation, deployment, Install, deploy, Installing, deploying 
summary: Puede instalar uno o varios dispositivos de almacenamiento StorageGRID cuando implemente StorageGRID por primera vez, o bien puede añadir nodos de almacenamiento del dispositivo más adelante como parte de una ampliación. Es posible que también se deba instalar un nodo de almacenamiento del dispositivo como parte de una operación de recuperación. 
---
= Información general sobre la instalación y la implementación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede instalar uno o varios dispositivos de almacenamiento StorageGRID cuando implemente StorageGRID por primera vez, o bien puede añadir nodos de almacenamiento del dispositivo más adelante como parte de una ampliación. Es posible que también se deba instalar un nodo de almacenamiento del dispositivo como parte de una operación de recuperación.

.Lo que necesitará
El sistema StorageGRID está utilizando la versión necesaria del software StorageGRID.

|===
| Dispositivo | Versión de StorageGRID requerida 


 a| 
SG6060 y SG606060 sin bandejas de ampliación
 a| 
11.1.1 o posterior



 a| 
SG6060 y SG6060X con bandejas de expansión (uno o dos)
 a| 
11.3 o posterior

*Nota:* Si agrega estantes de expansión después de la implementación inicial, debe utilizar la versión 11.4 o posterior.



 a| 
SGF6024
 a| 
11.3 o posterior

|===


== Tareas de instalación e implementación

Añadir un dispositivo de almacenamiento StorageGRID a un sistema StorageGRID incluye cuatro pasos principales:

. Preparación de la instalación:
+
** Preparación del sitio de instalación
** Desembalaje de las cajas y comprobación del contenido
** Obtención de equipos y herramientas adicionales
** Recopilación de direcciones IP e información de red
** Opcional: Configurar un servidor de gestión de claves (KMS) externo si planea cifrar todos los datos del dispositivo. Consulte detalles sobre la gestión de claves externas en las instrucciones para administrar StorageGRID.


. Instalar el hardware:
+
** Registrar el hardware
** Instalación del dispositivo en un armario o rack
** Instalar las unidades
** Instalación de bandejas de expansión opcionales (solo en el modelo SG6060 y SG6060X; máximo de dos bandejas de expansión)
** Cableado del aparato
** Conexión de los cables de alimentación y alimentación
** Ver los códigos de estado de inicio


. Configurar el hardware:
+
** Acceso a SANtricity System Manager para configurar los ajustes de SANtricity System Manager
** Acceder al instalador de dispositivos StorageGRID, establecer una dirección IP estática para el puerto de administración 1 en la controladora de almacenamiento y configurar los ajustes de IP de enlace y red necesarios para conectarse a las redes StorageGRID
** Acceso a la interfaz del controlador de administración de la placa base (BMC) en el controlador SG6000-CN
** Opcional: Habilitar el cifrado de nodos si tiene previsto utilizar un KMS externo para cifrar los datos del dispositivo.
** Opcional: Cambiar el modo RAID.


. Poner en marcha el dispositivo como nodo de almacenamiento:
+
|===
| Tarea | Instrucciones 


 a| 
Poner en marcha un nodo de almacenamiento del dispositivo en un nuevo sistema StorageGRID
 a| 
xref:deploying-appliance-storage-node.adoc[Ponga en marcha el nodo de almacenamiento del dispositivo]



 a| 
Añadir un nodo de almacenamiento del dispositivo a un sistema StorageGRID existente
 a| 
Instrucciones para ampliar un sistema StorageGRID



 a| 
Poner en marcha un nodo de almacenamiento del dispositivo como parte de una operación de recuperación de nodo de almacenamiento
 a| 
Instrucciones para recuperación y mantenimiento

|===


.Información relacionada
xref:preparing-for-installation.adoc[Preparación de la instalación (SG6000)]

xref:installing-hardware.adoc[Instalación del hardware (SG6000)]

xref:configuring-hardware.adoc[Configuración del hardware (SG6000)]

xref:../expand/index.adoc[Amplíe su grid]

xref:../maintain/index.adoc[Recuperación y mantenimiento]

xref:../admin/index.adoc[Administre StorageGRID]
