---
permalink: sg6000/maintaining-sg6000-appliance.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, maintain, maintaining, hardware, procedures, tasks 
summary: Es posible que tenga que realizar procedimientos de mantenimiento en el dispositivo SG6000. En los procedimientos descritos en esta sección se asume que el dispositivo ya se ha puesto en marcha como nodo de almacenamiento en un sistema StorageGRID. 
---
= Mantenimiento del dispositivo SG6000
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que tenga que realizar procedimientos de mantenimiento en el dispositivo SG6000. En los procedimientos descritos en esta sección se asume que el dispositivo ya se ha puesto en marcha como nodo de almacenamiento en un sistema StorageGRID.

Para evitar interrupciones del servicio, confirme que todos los demás nodos de almacenamiento están conectados al grid antes de apagar el dispositivo o apagar el dispositivo durante un período de mantenimiento programado cuando sean aceptables. Consulte la información acerca de xref:../monitor/monitoring-node-connection-states.adoc[supervisar los estados de conexión de los nodos].


IMPORTANT: Si alguna vez ha utilizado una regla de ILM que solo crea una copia de un objeto, debe apagar el dispositivo durante una ventana de mantenimiento programada. De lo contrario, es posible que pierda temporalmente el acceso a esos objetos durante cualquier procedimiento de mantenimiento que deje sin servicio un nodo de almacenamiento. Consulte la información acerca de xref:../ilm/index.adoc[gestionar objetos con gestión del ciclo de vida de la información].
