---
permalink: sg6000/optional-changing-raid-mode-sg6000-only.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, raid, raid mode, change, changing, modify, DDP, ddp16, raid6 
summary: Es posible cambiar a un modo RAID diferente en el dispositivo para responder a sus requisitos de almacenamiento y recuperación. Solo puede cambiar el modo antes de implementar el nodo de almacenamiento del dispositivo. 
---
= Opcional: Cambiar el modo RAID (sólo SG6000)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible cambiar a un modo RAID diferente en el dispositivo para responder a sus requisitos de almacenamiento y recuperación. Solo puede cambiar el modo antes de implementar el nodo de almacenamiento del dispositivo.

.Lo que necesitará
* Está utilizando cualquier cliente que pueda conectarse a StorageGRID.
* El cliente tiene un xref:../admin/web-browser-requirements.adoc[navegador web compatible].


.Acerca de esta tarea
Antes de implementar el dispositivo como un nodo de almacenamiento, puede seleccionar una de las siguientes opciones de configuración de volumen:

* *DDP*: Este modo utiliza dos unidades de paridad por cada ocho unidades de datos. Éste es el modo predeterminado y recomendado para todos los dispositivos. En comparación con RAID6, los DDP ofrecen mejor rendimiento del sistema, reducen los tiempos de recompilación después de fallos de unidad y facilitan la gestión.
* *DDP16*: Este modo utiliza dos unidades de paridad por cada 16 unidades de datos, lo que da como resultado una mayor eficiencia de almacenamiento en comparación con DDP. En comparación con RAID6, DDP16 ofrece un mejor rendimiento del sistema, menores tiempos de recompilación después de fallos de unidad, facilidad de gestión y una eficiencia de almacenamiento similar. Para utilizar el modo DDP16, la configuración debe contener al menos 20 unidades. DDP16 no ofrece protección contra pérdida de cajón.
* *RAID6*: Este modo utiliza dos unidades de paridad por cada 16 o más unidades de datos. Para utilizar el modo RAID 6, la configuración debe contener al menos 20 unidades. Aunque RAID6 puede aumentar la eficiencia de almacenamiento del dispositivo en comparación con DDP, no es recomendable para la mayoría de entornos StorageGRID.



IMPORTANT: Si alguno de los volúmenes ya está configurado o si StorageGRID se instaló anteriormente, al cambiar el modo RAID se quitan y se reemplazan los volúmenes. Se perderán todos los datos de estos volúmenes.

.Pasos
. Abra un explorador e introduzca una de las direcciones IP para la controladora de computación del dispositivo.
+
`*https://_Controller_IP_:8443*`

+
`_Controller_IP_` Es la dirección IP de la controladora de computación (no la controladora de almacenamiento) en cualquiera de las tres redes StorageGRID.

+
Aparece la página de inicio del instalador de dispositivos de StorageGRID.

. Seleccione *Avanzado* > *modo RAID*.
. En la página *Configurar el modo RAID*, seleccione el modo RAID deseado en la lista desplegable modo.
. Haga clic en *Guardar*.


.Información relacionada
http://mysupport.netapp.com/info/web/ECMP1658252.html["Sitio de documentación para sistemas E-Series y EF-Series de NetApp"^]
