---
permalink: sg6000/overview-of-installation-rest-apis.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, installation REST API, REST API, installation REST APIs, REST APIs, Appliance Installer API, Appliance Installer APIs, Install API, Install APIs, Installer API, Installer APIs, Installation API, Installation APIs, api, apis 
summary: 'StorageGRID proporciona dos API REST para realizar tareas de instalación: La API de instalación de StorageGRID y la API del instalador de dispositivos de StorageGRID.' 
---
= Información general sobre la instalación de API de REST
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID proporciona dos API REST para realizar tareas de instalación: La API de instalación de StorageGRID y la API del instalador de dispositivos de StorageGRID.

Ambas API utilizan la plataforma API de código abierto de Swagger para proporcionar la documentación de API. Swagger permite que tanto desarrolladores como no desarrolladores interactúen con la API en una interfaz de usuario que ilustra cómo responde la API a los parámetros y las opciones. En esta documentación se asume que está familiarizado con las tecnologías web estándar y el formato de datos JSON (notación de objetos JavaScript).


IMPORTANT: Cualquier operación de API que realice mediante la página web de documentos de API es una operación en directo. Tenga cuidado de no crear, actualizar o eliminar datos de configuración u otros datos por error.

Cada comando de API REST incluye la URL de la API, una acción HTTP, los parámetros de URL necesarios o opcionales y una respuesta de API esperada.



== API de instalación de StorageGRID

La API de instalación de StorageGRID solo está disponible cuando configura inicialmente el sistema StorageGRID y en el caso de que deba realizar una recuperación de nodo de administrador principal. Se puede acceder a la API de instalación a través de HTTPS desde Grid Manager.

Para acceder a la documentación de API, vaya a la página web de instalación del nodo de administración principal y seleccione *Ayuda* > *Documentación de API* en la barra de menús.

La API de instalación de StorageGRID incluye las siguientes secciones:

* *Config* -- Operaciones relacionadas con la versión del producto y las versiones de la API. Puede mostrar la versión de la versión del producto y las versiones principales de la API que admite esa versión.
* *Grid* -- Operaciones de configuración a nivel de cuadrícula. Puede obtener y actualizar la configuración de la cuadrícula, incluidos los detalles de la cuadrícula, las subredes de la red de cuadrícula, las contraseñas de la cuadrícula y las direcciones IP del servidor NTP y DNS.
* *NODES* -- Operaciones de configuración a nivel de nodo. Puede recuperar una lista de nodos de cuadrícula, eliminar un nodo de cuadrícula, configurar un nodo de cuadrícula, ver un nodo de cuadrícula y restablecer la configuración de un nodo de cuadrícula.
* *Aprovisionamiento* -- Operaciones de aprovisionamiento. Puede iniciar la operación de aprovisionamiento y ver el estado de la operación de aprovisionamiento.
* *Recuperación* -- Operaciones de recuperación del nodo de administración principal. Puede restablecer la información, cargar el paquete de recuperación, iniciar la recuperación y ver el estado de la operación de recuperación.
* *Paquete de recuperación* -- Operaciones para descargar el paquete de recuperación.
* *Sites* -- Operaciones de configuración a nivel de sitio. Puede crear, ver, eliminar y modificar un sitio.




== API del instalador de dispositivos de StorageGRID

Se puede acceder a la API del instalador de dispositivos de StorageGRID a través de HTTPS desde `_Controller_IP_:8443`.

Para acceder a la documentación de la API, vaya al instalador del dispositivo StorageGRID en el dispositivo y seleccione *Ayuda* > *Documentación de la API* en la barra de menús.

La API del instalador de dispositivos de StorageGRID incluye las siguientes secciones:

* *Clone* -- Operaciones para configurar y controlar la clonación de nodos.
* *Cifrado* -- Operaciones para administrar el cifrado y ver el estado del cifrado.
* *Configuración del hardware* -- Operaciones para configurar los ajustes del sistema en el hardware conectado.
* *Instalación* -- Operaciones para iniciar la instalación del aparato y para supervisar el estado de instalación.
* *Redes* -- Operaciones relacionadas con la configuración de red de Grid, Admin y Cliente para un dispositivo StorageGRID y los ajustes de puerto de dispositivo.
* *Setup* -- Operaciones para ayudar con la instalación inicial del dispositivo incluyendo solicitudes para obtener información sobre el sistema y actualizar el IP principal del nodo de administración.
* *SOPORTE* -- Operaciones para reiniciar el controlador y obtener registros.
* *Upgrade* -- Operaciones relacionadas con la actualización del firmware del dispositivo.
* *Uploadsg* -- Operaciones para cargar archivos de instalación de StorageGRID.

