---
permalink: sg6000/replacing-hardware-components-in-storage-controller-shelf.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, Replacing, replace, hardware, components, remove, removing, removal, install, installing, installation, storage controller shelf, Battery, Drive, Power canister, power supply, Fan canister, fan, Drive drawer 
summary: Si se produce un problema de hardware, es posible que deba sustituir un componente de la bandeja de controladoras de almacenamiento. 
---
= Sustituya los componentes de hardware en la bandeja de controladoras de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si se produce un problema de hardware, es posible que deba sustituir un componente de la bandeja de controladoras de almacenamiento.

.Lo que necesitará
* Tiene el procedimiento de sustitución del hardware E-Series.
* Ha localizado físicamente el dispositivo de almacenamiento en el que va a reemplazar componentes de hardware de la bandeja de almacenamiento en el centro de datos.
+
xref:locating-controller-in-data-center.adoc[Ubique la controladora en el centro de datos]



.Acerca de esta tarea
Para sustituir la batería en el controlador de almacenamiento, consulte las instrucciones de estas instrucciones para sustituir un controlador de almacenamiento. Estas instrucciones describen cómo extraer un controlador del aparato, extraer la batería del controlador, instalar la batería y sustituir el controlador.

Para obtener instrucciones sobre las otras unidades reemplazables de campo (FRU) en las bandejas de las controladoras, acceda a los procedimientos de E-Series para realizar el mantenimiento del sistema.

|===
| FRU | Consulte las instrucciones 


 a| 
Batería
 a| 
StorageGRID (estas instrucciones): Sustituir una controladora de almacenamiento



 a| 
Unidad
 a| 
E-Series:

* Sustitución de unidad (60 unidades)
* Sustitución de unidad (12 o 24 unidades)




 a| 
Contenedor de alimentación
 a| 
E-Series

* Sustituir contenedor de alimentación (60 unidades)
* Sustitución de la fuente de alimentación (12 o 24 unidades)




 a| 
Contenedor de ventilador (solo bandejas de 60 unidades)
 a| 
E-Series: Sustituir contenedor de ventilador (60 unidades)



 a| 
Cajón de unidades (solo bandejas de 60 unidades)
 a| 
E-Series: Sustitución del cajón de unidades (60 unidades)

|===
.Información relacionada
http://["Sitio de documentación para sistemas E-Series y EF-Series de NetApp"^]

xref:replacing-storage-controller-sg6000.adoc[Sustituya la controladora de almacenamiento]
