---
permalink: sg6000/upgrading-santricity-os-on-storage-controllers.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, controller, storage controller, upgrade, upgrading, SANtricity OS, SANtricity 
summary: 'Para garantizar el funcionamiento óptimo de la controladora de almacenamiento, debe actualizarse a la versión de mantenimiento más reciente del sistema operativo SANtricity que esté cualificado para su dispositivo StorageGRID. Consulte la herramienta de matriz de interoperabilidad de NetApp \(IMT\) para determinar qué versión debe utilizar. Si necesita ayuda, póngase en contacto con el soporte técnico.' 
---
= Actualizar el sistema operativo SANtricity en las controladoras de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para garantizar el funcionamiento óptimo de la controladora de almacenamiento, debe actualizarse a la versión de mantenimiento más reciente del sistema operativo SANtricity que esté cualificado para su dispositivo StorageGRID. Consulte la herramienta de matriz de interoperabilidad de NetApp (IMT) para determinar qué versión debe utilizar. Si necesita ayuda, póngase en contacto con el soporte técnico.

Siga uno de los siguientes procedimientos según la versión de SANtricity OS instalada actualmente:

* Si la controladora de almacenamiento utiliza el sistema operativo SANtricity 08.42.20.00 (11.42) o una versión posterior, use Grid Manager para llevar a cabo la actualización.
+
xref:upgrading-santricity-os-on-storage-controllers-using-grid-manager-sg6000.adoc[Actualizar el sistema operativo SANtricity en controladoras de almacenamiento mediante Grid Manager]

* Si la controladora de almacenamiento utiliza una versión de sistema operativo SANtricity anterior a 08.42.20.00 (11.42), use el modo de mantenimiento para realizar la actualización.
+
xref:upgrading-santricity-os-on-storage-controllers-using-maintenance-mode-sg6000.adoc[Actualizar el sistema operativo SANtricity en controladoras de almacenamiento mediante el modo de mantenimiento]




IMPORTANT: Al actualizar el sistema operativo SANtricity para el dispositivo de almacenamiento, debe seguir las instrucciones de la documentación de StorageGRID. Si usa otras instrucciones, el aparato podría quedar inoperativo.

.Información relacionada
https://["Herramienta de matriz de interoperabilidad de NetApp"^]

https://["Descargas de NetApp: Dispositivo de StorageGRID"^]

xref:../monitor/index.adoc[Supervisión y solución de problemas]
