---
permalink: audit/client-write-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, messages, client write, OVWR, SDEL, SPOS, SPUT, SUPD, WDEL, WPUT, S3, swift 
summary: Los mensajes de auditoría de escritura de cliente se registran cuando una aplicación cliente S3 o Swift hace una solicitud para crear o modificar un objeto. 
---
= El cliente escribe mensajes de auditoría
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los mensajes de auditoría de escritura de cliente se registran cuando una aplicación cliente S3 o Swift hace una solicitud para crear o modificar un objeto.

|===
| Codificación | Descripción | Utilizado por | Consulte 


 a| 
OVWR
 a| 
Objeto Overwrite: Registra una transacción para sobrescribir un objeto con otro.
 a| 
Clientes S3

Clientes Swift
 a| 
xref:ovwr-object-overwrite.adoc[OVWR: Sobrescritura de objetos]



 a| 
SDEL
 a| 
S3 DELETE: Registra una transacción realizada correctamente para eliminar un objeto o bloque.

*Nota:* Si la transacción opera en un subrecurso, el mensaje de auditoría incluirá el campo S3SR.
 a| 
Cliente S3
 a| 
xref:sdel-s3-delete.adoc[SDEL: ELIMINACIÓN DE S3]



 a| 
SPO
 a| 
S3 POST: Registra una transacción realizada correctamente para restaurar un objeto del almacenamiento AWS Glacier en un Pool de almacenamiento en cloud.
 a| 
Cliente S3
 a| 
xref:spos-s3-post.adoc[SPOS: PUBLICACIÓN DE S3]



 a| 
SPUT
 a| 
S3 PUT: Registra una transacción realizada correctamente para crear un nuevo objeto o bloque.

*Nota:* Si la transacción opera en un subrecurso, el mensaje de auditoría incluirá el campo S3SR.
 a| 
Cliente S3
 a| 
xref:sput-s3-put.adoc[SPUT: S3 PUT]



 a| 
SUPD
 a| 
S3 Metadata Updated: Registra una transacción correcta para actualizar los metadatos de un objeto o bloque existente.
 a| 
Cliente S3
 a| 
xref:supd-s3-metadata-updated.adoc[SUPD: Se han actualizado metadatos S3]



 a| 
¡WDEL
 a| 
Swift DELETE: Registra una transacción realizada correctamente para eliminar un objeto o un contenedor.
 a| 
Cliente Swift
 a| 
xref:wdel-swift-delete.adoc[WDEL: ELIMINACIÓN de Swift]



 a| 
WPUT
 a| 
Swift PUT: Registra una transacción correcta para crear un nuevo objeto o contenedor.
 a| 
Cliente Swift
 a| 
xref:wput-swift-put.adoc[WPUT: SWIFT PUT]

|===