---
permalink: audit/event-specific-data.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, event, data 
summary: Cada mensaje de auditoría del registro de auditoría registra datos específicos de un evento del sistema. 
---
= Datos específicos de un evento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada mensaje de auditoría del registro de auditoría registra datos específicos de un evento del sistema.

Siguiendo la abertura `[AUDT:` contenedor que identifica el mensaje en sí, el siguiente conjunto de atributos proporciona información acerca del evento o la acción descrita por el mensaje de auditoría. Estos atributos se resaltan en el siguiente ejemplo:

[]
====
2018-12-SUST08:24:45.921845 [AUDT:*\[RSLT\(FC32\):SUCS\]* *\[TIME\(UI64\):11454 60025621595611246499\[SUST08\[SAIP\(IPAD\):"10.224.0 60025621595611246499.100 60025621595611246499"\[S3AI\(ECSTR\):"CSTR\\\\"[CSTR\][CSTR\\][CSTR]\\\\[CSTR][CSTR]\\\\[CSTR][CSTR][CSTR\\\\\\\\"[CSTR][CSTR][CSTR][CSTR\\\\\\\\\\\[CSTR][CSTR][CSTR][CSTR][CSTR][CSTR\\\\\\\\\\\[CSTR][CSTR][CSTR][CSTR][CSTR][CSTR][CSTR][CSTR\\\\\\\\\\\\\\[KJC][KJC\\\ 15552417629170647261 12281045 1543998285921845 10 30720

====
La `ATYP` elemento (subrayado en el ejemplo) identifica qué evento generó el mensaje. Este mensaje de ejemplo incluye el código DE mensaje SHEA ([ATYP(FC32):SHEA]), que indica que se generó mediante una solicitud de ENCABEZADO S3 correcta.

.Información relacionada
xref:common-elements-in-audit-messages.adoc[Elementos comunes de los mensajes de auditoría]

xref:audit-messages-main.adoc[Auditar mensajes]
