---
permalink: audit/wget-swift-get.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, WGET, Swift GET 
summary: Cuando un cliente de Swift emite una transacción GET, se realiza una solicitud para recuperar un objeto, enumerar los objetos de un contenedor o enumerar los contenedores en una cuenta. El servidor emite este mensaje si la transacción se realiza correctamente. 
---
= WGET: Swift GET
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando un cliente de Swift emite una transacción GET, se realiza una solicitud para recuperar un objeto, enumerar los objetos de un contenedor o enumerar los contenedores en una cuenta. El servidor emite este mensaje si la transacción se realiza correctamente.

|===
| Codificación | Campo | Descripción 


 a| 
CBID
 a| 
Identificador de bloque de contenido
 a| 
Identificador único del bloque de contenido solicitado. Si el CBID es desconocido, este campo se establece en 0. Este campo no incluye las operaciones de las cuentas y los contenedores.



 a| 
CSIZ
 a| 
Tamaño de contenido
 a| 
El tamaño del objeto recuperado en bytes. Este campo no incluye las operaciones de las cuentas y los contenedores.



 a| 
HTRH
 a| 
Encabezado de solicitud HTTP
 a| 
Lista de los nombres de encabezado y valores registrados de la solicitud HTTP como seleccionados durante la configuración.

*Nota:* `X-Forwarded-For` se incluye automáticamente si está presente en la solicitud y si la `X-Forwarded-For` El valor es diferente de la dirección IP del remitente de la solicitud (campo de auditoría SAIP).



 a| 
TRANSFORMACIÓN DIGITAL
 a| 
Código de resultado
 a| 
Resultado DE LA transacción GET. El resultado es siempre

SUCS: Exitoso



 a| 
SAIP
 a| 
Dirección IP del cliente solicitante
 a| 
La dirección IP de la aplicación cliente que realizó la solicitud.



 a| 
TIEMPO
 a| 
Tiempo
 a| 
Tiempo de procesamiento total de la solicitud en microsegundos.



 a| 
TLIP
 a| 
Dirección IP del equilibrador de carga de confianza
 a| 
Si la solicitud se enrutó por un equilibrador de carga de capa 7 de confianza, la dirección IP del equilibrador de carga.



 a| 
UUID
 a| 
Identificador único universal
 a| 
El identificador del objeto dentro del sistema StorageGRID.



 a| 
WACC
 a| 
ID de cuenta de Swift
 a| 
El ID de cuenta único especificado por el sistema StorageGRID.



 a| 
WCON
 a| 
Contenedor Swift
 a| 
El nombre del contenedor Swift. Las operaciones en cuentas no incluyen este campo.



 a| 
WOBJ
 a| 
Objeto Swift
 a| 
El identificador del objeto Swift. Este campo no incluye las operaciones de las cuentas y los contenedores.



 a| 
WUSR
 a| 
Usuario de la cuenta de Swift
 a| 
El nombre de usuario de la cuenta de Swift que identifica de manera exclusiva al cliente que realiza la transacción.

|===