---
settings:
  name: StorageGRID
  search: storagegrid-enable,storagegrid-116
  downlevel: true
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  versions:
  - version-number: '11.6'
    url: "/storagegrid-116"
  - version-number: '12.0'
    url: "/storagegrid"
  - version-number: '11.9'
    url: "/storagegrid-119"
  - version-number: '11.8'
    url: "/storagegrid-118"
  - version-number: '11.7'
    url: "/storagegrid-117"
  - version-number: '11.5'
    url: "/storagegrid-115"
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de StorageGRID 11,6
    url: "/index.html"
  - title: Notas de la versión
    url: "/release-notes/index.html"
  - title: Manos a la obra
    entries:
    - section: primer
    - section: network
  - title: Instale y mantenga el hardware del dispositivo
    entries:
    - section: sg100-1000
    - section: sg6000
    - section: sg5700
    - section: sg5600
  - title: Instale y actualice el software
    entries:
    - section: upgrade
    - section: rhel
    - section: ubuntu
    - section: vmware
  - title: Realizar la administración del sistema
    entries:
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
  - title: Utilice StorageGRID
    entries:
    - section: tenant
    - section: s3
    - section: swift
  - title: Supervisar y mantener StorageGRID
    entries:
    - section: monitor
    - section: expand
    - section: maintain
    - section: audit
  - title: Habilite StorageGRID
    url: "/storagegrid-enable.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: StorageGRID documentation
  repo: storagegrid-family
