---
settings:
  name: StorageGRID
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  versions:
  - name: StorageGRID
    url: "/storagegrid-116"
    version-number: '11.6'
  - name: StorageGRID
    url: "/storagegrid-115"
    version-number: '11.5'
  - name: StorageGRID
    url: https://mysupport.netapp.com/documentation/docweb/index.html?productID=63374&language=en-US
    version-number: '11.4'
  - name: StorageGRID
    url: https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61023&archive=true
    version-number: '11.3'
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr
sidebar:
  entries:
  - title: Documentos de StorageGRID 11.6
    url: "/index.html"
  - section: release-notes
  - title: Manos a la obra
    entries:
    - section: primer
    - section: network
  - title: Instale y mantenga el hardware del dispositivo
    entries:
    - section: sg100-1000
    - section: sg6000
    - section: sg5700
    - section: sg5600
  - title: Instale y actualice el software
    entries:
    - section: upgrade
    - section: rhel
    - section: ubuntu
    - section: vmware
  - title: Realizar la administración del sistema
    entries:
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
  - title: Utilice StorageGRID
    entries:
    - section: tenant
    - section: s3
    - section: swift
  - title: Supervisar y mantener StorageGRID
    entries:
    - section: monitor
    - section: expand
    - section: maintain
    - section: audit
  - title: Habilite StorageGRID
    url: "/storagegrid-enable.html"
  - title: Versiones anteriores
    url: "/earlier-versions.html"
  - title: Avisos legales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Manos a la obra
    links:
    - title: Notas de la versión
      url: "/release-notes/index.html"
    - title: Novedades
      url: "/upgrade/whats-new.html"
    - title: Imprimador de rejilla
      url: "/primer/index.html"
    - title: Directrices de red
      url: "/network/index.html"
  - title: Instale el hardware de mantenimiento
    links:
    - title: Servicios de aplicaciones SG100 y SG1000
      url: "/sg100-1000/index.html"
    - title: Dispositivos de almacenamiento SG6000
      url: "/sg6000/index.html"
    - title: Dispositivos de almacenamiento SG5700
      url: "/sg5700/index.html"
    - title: Dispositivos de almacenamiento SG5600
      url: "/sg5600/index.html"
  - title: Instale el software de actualización
    links:
    - title: Instale Red Hat Enterprise Linux o CentOS
      url: "/rhel/index.html"
    - title: Instalar Ubuntu o Debian
      url: "/ubuntu/index.html"
    - title: Instale VMware
      url: "/vmware/index.html"
    - title: Actualizar el software de
      url: "/upgrade/index.html"
  - title: Configure la cuadrícula
    links:
    - title: Administre StorageGRID
      url: "/admin/index.html"
    - title: Gestión de objetos con ILM
      url: "/ilm/index.html"
    - title: Endurecimiento del sistema
      url: "/harden/index.html"
    - title: Configure StorageGRID para FabricPool
      url: "/fabricpool/index.html"
  - title: Gestione objetos
    links:
    - title: Usar una cuenta de inquilino
      url: "/tenant/index.html"
    - title: Use S3
      url: "/s3/index.html"
    - title: Use Swift
      url: "/swift/index.html"
  - title: Mantenimiento del monitor
    links:
    - title: Supervise la solución de problemas
      url: "/monitor/index.html"
    - title: Amplíe su grid
      url: "/expand/index.html"
    - title: Recuperación mantener
      url: "/maintain/index.html"
    - title: Revisar los registros de auditoría
      url: "/audit/index.html"
  - title: Tutoriales de demos
    links:
    - title: Aprenda cómo habilitar StorageGRID
      url: https://docs.netapp.com/us-en/storagegrid-enable/index.html
    - title: Biblioteca de vídeos de StorageGRID
      url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7nh2wGRA65iulXhtXwLiqrY
    - title: Servicios de aprendizaje de NetApp
      url: https://www.netapp.com/support-and-training/netapp-university/
  - title: Más recursos
    links:
    - title: Página de soporte de StorageGRID
      url: https://mysupport.netapp.com/site/products/all/details/5d9f1107e01d9c0001ee50f6/downloads-tab
    - title: Herramienta de matriz de interoperabilidad de NetApp (IMT)
      url: https://mysupport.netapp.com/matrix
    - title: Base de conocimientos de StorageGRID
      url: https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID
    - title: Blog de NetApp
      url: https://netapp.com/blog/
    - title: Comunidad de NetApp
      url: https://community.netapp.com/
  - title: Versiones anteriores
    links:
    - title: Documentación de StorageGRID 11.5
      url: https://docs.netapp.com/sgws-115/index.jsp
    - title: Documentación de StorageGRID 11.4
      url: https://docs.netapp.com/sgws-114/index.jsp
    - title: Documentación de StorageGRID 11.3
      url: https://docs.netapp.com/sgws-113/index.jsp
    - title: Documentación de StorageGRID 11.2
      url: https://docs.netapp.com/sgws-112/index.jsp
