---
sidebar: sidebar 
permalink: storagegrid-enable.html 
keywords: storagegrid, how to enable, third-party solutions, tools, applications, examples 
summary: Obtenga información sobre cómo probar y habilitar las aplicaciones en su entorno de StorageGRID. 
---
= Cómo habilitar StorageGRID en su entorno
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Obtenga información sobre cómo probar y habilitar las aplicaciones en su entorno de StorageGRID.

Vaya a la https://["storagegrid-enable"^] sitio de documentos para encontrar ejemplos y libros de cocina que se amplían en la documentación del producto en este sitio. El sitio *storagegrid-enable* también describe algunos pasos siguientes para evaluar e integrar con StorageGRID.

Se incluye la siguiente información:

* Listas de soluciones de terceros validadas para versiones anteriores y actuales de StorageGRID.
* Guías de características de productos. Por ejemplo, estas guías proporcionan información detallada para la creación de pools de almacenamiento en cloud.
* Guías de herramientas y aplicaciones.
* Ejemplos de API para usar funciones de StorageGRID como el cifrado S3 y el bloqueo de objetos S3.

