---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: Debe comprender cómo se verá afectado su sistema StorageGRID durante la actualización. 
---
= Cómo se ve afectado el sistema durante la actualización
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe comprender cómo se verá afectado su sistema StorageGRID durante la actualización.



== Las actualizaciones de StorageGRID no son disruptivas

El sistema StorageGRID puede procesar y recuperar datos de las aplicaciones cliente durante el proceso de actualización. Los nodos de grid se ven inactivos de uno en uno durante la actualización, por lo que no hay una hora cuando todos los nodos de grid no están disponibles.

Para permitir la disponibilidad continua, debe asegurarse de que los objetos se almacenen de forma redundante con las políticas de ILM apropiadas. También debe asegurarse de que todos los clientes externos de S3 o Swift estén configurados para enviar solicitudes a una de las siguientes:

* Un extremo de StorageGRID configurado como grupo de alta disponibilidad
* Un equilibrador de carga de terceros de alta disponibilidad
* Múltiples nodos de puerta de enlace para cada cliente
* Varios nodos de almacenamiento para cada cliente




== El firmware del dispositivo se ha actualizado

Durante la actualización de StorageGRID 11.6:

* Todos los nodos de dispositivos StorageGRID se actualizan automáticamente a la versión de firmware 3.6 de StorageGRID Appliance Installer.
* Los dispositivos SG6060 y SGF6024 se actualizan automáticamente a la versión de firmware del BIOS 3B07.EX y a la versión de firmware del BMC 3.93.07.
* Los dispositivos SG100 y SG1000 se actualizan automáticamente a la versión 3B12.EC del firmware del BIOS y a la versión 4.67.07 del firmware del BMC.




== Es posible que se activen alertas

Es posible que se activen alertas cuando se inician y se detienen los servicios y cuando el sistema StorageGRID funciona como un entorno de versiones mixtas (algunos nodos de grid que ejecutan una versión anterior, mientras que otros se han actualizado a una versión posterior). Es posible que se activen otras alertas una vez que se complete la actualización.

Por ejemplo, es posible que aparezca la alerta *no se puede comunicar con el nodo* cuando se detienen los servicios, o que aparezca la alerta *error de comunicación* de Cassandra cuando algunos nodos se han actualizado a StorageGRID 11.6 pero otros nodos todavía ejecutan StorageGRID 11.5. En general, estas alertas se borran cuando se completa la actualización.

La alerta de *colocación de ILM inalcanzable* puede activarse cuando se detienen los nodos de almacenamiento durante la actualización a StorageGRID 11.6. Esta alerta podría persistir durante un día después de que se completa la actualización.

Si utiliza valores personalizados para las marcas de agua del volumen de almacenamiento, la alerta *anulación de Marca de agua de sólo lectura baja* puede activarse después de finalizar la actualización. Consulte xref:../monitor/troubleshoot-low-watermark-alert.adoc[Solucionar los problemas de las alertas de anulación de la Marca de agua de sólo lectura baja] para obtener más detalles.

Una vez completada la actualización, puede revisar cualquier alerta relacionada con la actualización seleccionando *Alertas resueltas recientemente* o *Alertas actuales* en el Panel de Grid Manager.



== Se generan muchas notificaciones SNMP

Tenga en cuenta que es posible que se genere un gran número de notificaciones SNMP cuando se detengan los nodos de grid y se reinician durante la actualización. Para evitar notificaciones excesivas, anule la selección de la casilla de verificación *Activar notificaciones de agente SNMP* (*CONFIGURACIÓN* > *Supervisión* > *agente SNMP*) para desactivar las notificaciones SNMP antes de iniciar la actualización. A continuación, vuelva a habilitar las notificaciones cuando finalice la actualización.



== Los cambios de configuración están restringidos


NOTE: La lista de cambios de configuración restringidos puede cambiar de una versión a otra. Cuando actualice a otra versión de StorageGRID, consulte la lista de las instrucciones de actualización correspondientes.

Hasta que finalice la tarea *Activar nueva función*:

* No realice ningún cambio en la configuración de la cuadrícula.
* No se debe cambiar la configuración de nivel de auditoría ni configurar un servidor de syslog externo.
* No active ni desactive ninguna nueva función.
* No actualice la configuración de ILM. De lo contrario, es posible que experimente un comportamiento de ILM inconsistente e inesperado.
* No aplique una revisión ni recupere un nodo de cuadrícula.
* No puede gestionar grupos de alta disponibilidad, interfaces VLAN ni extremos de equilibrador de carga mientras se actualiza a StorageGRID 11.6.


Hasta que finalice la tarea *pasos de actualización final*:

* No realice un procedimiento de expansión.
* No realice un procedimiento de retirada de servicio.




== No se pueden ver los detalles de los bloques ni gestionar los bloques desde el administrador de inquilinos

Durante la actualización a StorageGRID 11.6 (es decir, mientras el sistema está funcionando como un entorno de versión mixta), no se pueden ver detalles del bloque ni gestionar bloques con el administrador de inquilinos. Aparece uno de los siguientes errores en la página Cuches del Administrador de inquilinos:

* «'no puede utilizar esta API mientras actualiza a 11.6».
* "'no se pueden ver los detalles de control de versiones de bloques en el Gestor de inquilinos mientras se actualiza a 11.6.'"


Este error se resolverá una vez que se complete la actualización a la versión 11.6.

.Solución alternativa
Mientras la actualización 11.6 está en curso, utilice las siguientes herramientas para ver detalles de bloques o gestionar bloques, en lugar de utilizar el Gestor de inquilinos:

* Para realizar operaciones estándar de S3 en un bloque, utilice la API REST de S3 o la API de gestión de inquilinos.
* Para realizar operaciones personalizadas de StorageGRID en un bloque (por ejemplo, ver y modificar el nivel de coherencia de bloques, habilitar o deshabilitar actualizaciones del tiempo de último acceso, o configurar la integración de búsqueda), use la API de gestión de inquilinos.


Consulte xref:../tenant/understanding-tenant-management-api.adoc[Comprender la API de gestión de inquilinos] y.. xref:../s3/index.adoc[Use S3] si desea obtener instrucciones.
