---
permalink: sg100-1000/replacing-services-appliance.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, Replacing, replace, remove, removing, removal, install, installing, installation 
summary: Es posible que deba sustituir el aparato si no funciona de forma óptima o si ha fallado. 
---
= Sustituya el aparato de servicios
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que deba sustituir el aparato si no funciona de forma óptima o si ha fallado.

.Lo que necesitará
* Tiene un aparato de repuesto con el mismo número de pieza que el aparato que va a sustituir.
* Tiene etiquetas para identificar cada cable que está conectado al dispositivo.
* Ya tienes xref:locating-controller-in-data-center.adoc[ubicación física del aparato].
* El aparato se ha estado xref:placing-appliance-into-maintenance-mode.adoc[se colocó en modo de mantenimiento].


.Acerca de esta tarea
No se podrá acceder al nodo StorageGRID mientras sustituye el dispositivo. Si el aparato funciona lo suficiente, puede realizar un apagado controlado al inicio de este procedimiento.


NOTE: Si va a sustituir el dispositivo antes de instalar el software StorageGRID, es posible que no pueda acceder al instalador de dispositivos StorageGRID inmediatamente después de completar este procedimiento. Aunque puede acceder al instalador del dispositivo StorageGRID desde otros hosts de la misma subred que el dispositivo, no puede acceder al mismo desde hosts de otras subredes. Esta condición debe resolverse dentro de los 15 minutos (cuando se agota cualquier entrada de caché ARP para el tiempo original del dispositivo) o puede borrar la condición de inmediato mediante la purga manual de todas las entradas antiguas de la caché ARP desde el enrutador o la puerta de enlace local.

.Pasos
. Cuando el aparato se haya puesto en modo de mantenimiento, apague el aparato.
+
.. Inicie sesión en el nodo de grid:
+
... Introduzca el siguiente comando: `ssh admin@_grid_node_IP_`
... Introduzca la contraseña que aparece en `Passwords.txt` archivo.
... Introduzca el siguiente comando para cambiar a la raíz: `su -`
... Introduzca la contraseña que aparece en `Passwords.txt` archivo.
+
Cuando ha iniciado sesión como root, el símbolo del sistema cambia de `$` para `#`.



.. Apague el aparato: +
`*shutdown -h now*`


. Utilice uno de estos dos métodos para verificar que el aparato está apagado:
+
** El LED del indicador de alimentación de la parte frontal del aparato está apagado.
** La página Power Control de la interfaz del BMC indica que el aparato está apagado.


. Si las redes StorageGRID conectadas al dispositivo utilizan servidores DHCP, actualice los ajustes de DNS/red y dirección IP.
+
.. Busque la etiqueta de dirección MAC en la parte frontal del dispositivo y determine la dirección MAC para el puerto de red de administración.
+

NOTE: La etiqueta de dirección MAC incluye la dirección MAC para el puerto de gestión del BMC.

+
Para determinar la dirección MAC del puerto de red de administración, debe agregar *2* al número hexadecimal de la etiqueta. Por ejemplo, si la dirección MAC de la etiqueta termina en *09*, la dirección MAC del puerto de administración finalizará en *0B*. Si la dirección MAC de la etiqueta termina en *(_y_)FF*, la dirección MAC del puerto de administración finalizará en *(_y_+1)01*. Puede realizar este cálculo fácilmente abriendo Calculadora en Windows, establecerlo en modo Programador, seleccionando hex, escribiendo la dirección MAC y, a continuación, escribiendo *+ 2 =*.

.. Solicite al administrador de red que asocie el DNS/red y la dirección IP del dispositivo que ha quitado con la dirección MAC del dispositivo de reemplazo.
+

IMPORTANT: Debe asegurarse de que todas las direcciones IP del dispositivo original se han actualizado antes de aplicar alimentación al dispositivo de sustitución. De lo contrario, el dispositivo obtendrá nuevas direcciones IP de DHCP cuando se arranca y es posible que no pueda volver a conectarse a StorageGRID. Este paso se aplica a todas las redes StorageGRID conectadas al dispositivo.

+

NOTE: Si el dispositivo original utilizaba una dirección IP estática, el dispositivo nuevo adoptará automáticamente las direcciones IP del dispositivo que ha quitado.



. Retire y sustituya el aparato:
+
.. Etiquete los cables y desconecte los cables y cualquier transceptor de red.
+

IMPORTANT: Para evitar un rendimiento degradado, no gire, pliegue, pellizque ni pellizque los cables.

.. Retire el dispositivo que ha fallado del armario o rack.
.. Transfiera las dos fuentes de alimentación, ocho ventiladores de refrigeración y dos SSD del dispositivo con error al dispositivo de reemplazo.
+
Siga las instrucciones proporcionadas para sustituir estos componentes.

.. Instale el dispositivo de repuesto en el armario o rack.
.. Reemplace los cables y cualquier transceptor óptico.
.. Encienda el dispositivo y supervise los LED del dispositivo y los códigos de inicio.
+
Utilice la interfaz de BMC para supervisar el estado de inicio.



. Confirme que el nodo del dispositivo aparece en Grid Manager y que no aparece ninguna alerta.


.Información relacionada
xref:installing-appliance-in-cabinet-or-rack-sg100-and-sg1000.adoc[Instalar el dispositivo en un armario o rack (SG100 y SG1000)]

xref:viewing-status-indicators-on-sg100-and-sg1000-appliances.adoc[Ver los indicadores de estado de los aparatos SG100 y SG1000]

xref:viewing-boot-up-codes-for-appliance-sg100-and-sg1000.adoc[Ver los códigos de arranque del dispositivo]
