---
permalink: sg100-1000/sg100-and-sg1000-applications.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, applications, how to use, services 
summary: Puede configurar los dispositivos de servicios StorageGRID de diversas formas para proporcionar servicios de puerta de enlace, así como redundancia de algunos servicios de administración de grid. 
---
= Aplicaciones SG100 y SG1000
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar los dispositivos de servicios StorageGRID de diversas formas para proporcionar servicios de puerta de enlace, así como redundancia de algunos servicios de administración de grid.

Los dispositivos se pueden implementar de las siguientes formas:

* Agregue a una cuadrícula nueva o existente como nodo de puerta de enlace
* Añada a un grid nuevo como nodo de administrador principal o no primario, o a un grid existente como nodo de administrador no primario
* Opere como un nodo de puerta de enlace y un nodo de administración (principal o no primario) al mismo tiempo


El dispositivo facilita el uso de grupos de alta disponibilidad (ha) y el equilibrio de carga inteligente para las conexiones de la ruta de datos S3 o Swift.

Los siguientes ejemplos describen cómo puede maximizar las funcionalidades del dispositivo:

* Utilice dos dispositivos SG100 o dos SG1000 para proporcionar servicios de puerta de enlace configurándolos como nodos de puerta de enlace.
+

IMPORTANT: No instale los dispositivos de servicio SG100 y SG1000 en el mismo sitio. El rendimiento puede ser impredecible.

* Utilice dos dispositivos SG100 o dos SG1000 para ofrecer redundancia en algunos servicios de administración de grid. Para ello, configure cada dispositivo como nodos de administración.
* Utilice dos dispositivos SG100 o dos SG1000 para ofrecer servicios de equilibrio de carga y configuración de tráfico de alta disponibilidad a los que se accede a través de una o más direcciones IP virtuales. Para ello, configure los dispositivos como cualquier combinación de nodos de administrador o nodos de puerta de enlace y añada ambos nodos al mismo grupo de alta disponibilidad.
+

IMPORTANT: Si se utilizan nodos de administrador y nodos de puerta de enlace en el mismo grupo de alta disponibilidad, los puertos de CLB (equilibrador de carga de conexión) y los puertos solo de nodo de administración no se conmutarán al nodo de respaldo. Para obtener instrucciones sobre cómo configurar grupos de alta disponibilidad, consulte las instrucciones para administrar StorageGRID.

+

NOTE: El servicio CLB está obsoleto.



Cuando se utiliza con dispositivos de almacenamiento StorageGRID, tanto el SG100 como los dispositivos de servicios SG1000 permiten la implementación de grids de dispositivo únicamente sin dependencias en hipervisores externos o hardware informático.

.Información relacionada
xref:../admin/index.adoc[Administre StorageGRID]
