---
permalink: ubuntu/required-materials.html 
sidebar: sidebar 
keywords: installation materials ubuntu debian 
summary: Antes de instalar StorageGRID, debe recopilar y preparar los materiales necesarios. 
---
= Materiales requeridos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar StorageGRID, debe recopilar y preparar los materiales necesarios.

|===
| Elemento | Notas 


 a| 
Licencia de StorageGRID de NetApp
 a| 
Debe tener una licencia de NetApp válida y con firma digital.

*Nota*: En el archivo de instalación de StorageGRID se incluye una licencia de no producción, que puede utilizarse para probar y probar cuadrículas de concepto.



 a| 
Archivo de instalación de StorageGRID
 a| 
Debe xref:downloading-and-extracting-storagegrid-installation-files.adoc[Descargue el archivo de instalación de StorageGRID y extraiga los archivos].



 a| 
Portátil de servicio
 a| 
El sistema StorageGRID se instala a través de un ordenador portátil de servicio.

El portátil de servicio debe tener:

* Puerto de red
* Cliente SSH (por ejemplo, PuTTY)
* xref:../admin/web-browser-requirements.adoc[Navegador web compatible]




 a| 
Documentación de StorageGRID
 a| 
* xref:../release-notes/index.adoc[Notas de la versión]
* xref:../admin/index.adoc[Instrucciones para administrar StorageGRID]


|===
.Información relacionada
https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^]
