---
permalink: harden/hardening-guidelines-for-software-upgrades.html 
sidebar: sidebar 
keywords: Hardening guidelines, upgrades 
summary: Debe mantener su sistema StorageGRID y los servicios relacionados actualizados para defender los ataques. 
---
= Directrices de refuerzo para las actualizaciones de software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe mantener su sistema StorageGRID y los servicios relacionados actualizados para defender los ataques.



== Actualice al software StorageGRID

Siempre que sea posible, debe actualizar el software StorageGRID a la versión principal más reciente o a la versión principal anterior. Mantener la StorageGRID actualizada ayuda a reducir la cantidad de tiempo que las vulnerabilidades conocidas están activas y reduce el área general de la superficie de ataque. Además, las versiones más recientes de StorageGRID a menudo contienen funciones de seguridad reforzada que no se incluyen en las versiones anteriores.

Cuando se necesita una corrección, NetApp prioriza la creación de actualizaciones para las versiones más recientes. Es posible que algunos parches no sean compatibles con versiones anteriores.

Para descargar las versiones y correcciones urgentes de StorageGRID más recientes, vaya a la página de descarga del software StorageGRID. Para obtener instrucciones paso a paso para actualizar el software StorageGRID, consulte las instrucciones para actualizar StorageGRID. Para obtener instrucciones sobre cómo aplicar una revisión, consulte las instrucciones de recuperación y mantenimiento.



== Actualizaciones a servicios externos

Los servicios externos pueden tener vulnerabilidades que afectan indirectamente a StorageGRID. Debe asegurarse de que los servicios de los que depende StorageGRID se mantengan actualizados. Estos servicios incluyen LDAP, KMS (servidor KMIP o KMS), DNS y NTP.

Utilice la herramienta matriz de interoperabilidad de NetApp para obtener una lista de las versiones compatibles.



== Actualizaciones a hipervisores

Si los nodos de StorageGRID se ejecutan en VMware u otro hipervisor, debe asegurarse de que el software y el firmware del hipervisor estén actualizados.

Utilice la herramienta matriz de interoperabilidad de NetApp para obtener una lista de las versiones compatibles.



== *Actualizar a nodos Linux*

Si los nodos de StorageGRID utilizan plataformas host Linux, debe asegurarse de que las actualizaciones de seguridad y del kernel se apliquen al sistema operativo host. Además, debe aplicar actualizaciones de firmware al hardware vulnerable cuando estas actualizaciones estén disponibles.

Utilice la herramienta matriz de interoperabilidad de NetApp para obtener una lista de las versiones compatibles.

.Información relacionada
https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Descargas de NetApp: StorageGRID"^]

xref:../upgrade/index.adoc[Actualizar el software de]

xref:../maintain/index.adoc[Recuperación y mantenimiento]

https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^]
