---
permalink: swift/history-of-swift-api-support-in-storagegrid.html 
sidebar: sidebar 
keywords: swift api support history 
summary: Debe conocer los cambios en la compatibilidad del sistema StorageGRID con la API DE REST de Swift. 
---
= Historial de soporte de la API de Swift en StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe estar al tanto de los cambios en la compatibilidad del sistema StorageGRID con la API DE REST de Swift.

|===
| Liberar | Comentarios 


 a| 
11.6
 a| 
Cambios editoriales menores.



 a| 
11.5
 a| 
Se ha eliminado el control de consistencia débil. En su lugar, se utilizará el nivel de consistencia disponible.



 a| 
11.4
 a| 
Se ha agregado compatibilidad con TLS 1.3 y se ha actualizado la lista de conjuntos de cifrado TLS compatibles. CLB está en desuso. Se añadió la descripción de la relación entre ILM y la configuración de consistencia.



 a| 
11.3
 a| 
Las operaciones de PUT Object actualizadas para describir el impacto de las reglas de ILM que utilizan la colocación síncrona en el procesamiento (las opciones equilibradas y estrictas del comportamiento de procesamiento). Se ha agregado una descripción de las conexiones de cliente que utilizan extremos de equilibrador de carga o grupos de alta disponibilidad. Lista actualizada de conjuntos de cifrado TLS admitidos. Ya no se admiten los cifrados TLS 1.1.



 a| 
11.2
 a| 
Cambios editoriales menores en el documento.



 a| 
11.1
 a| 
Se añadió compatibilidad con el uso de HTTP para conexiones de clientes Swift a los nodos de grid. Se han actualizado las definiciones de controles de coherencia.



 a| 
11.0
 a| 
Se ha agregado soporte para 1,000 contenedores por cada cuenta de inquilino.



 a| 
10.3
 a| 
Actualizaciones administrativas y correcciones en el documento. Se han eliminado secciones para configurar certificados de servidor personalizados.



 a| 
10.2
 a| 
Soporte inicial de la API Swift por el sistema StorageGRID. La versión compatible actualmente es la API de almacenamiento de objetos Swift de OpenStack v1.

|===