---
permalink: swift/swift-rest-api-supported-operations.html 
sidebar: sidebar 
keywords: OpenStack, Swift API, REST API 
summary: El sistema StorageGRID admite la mayoría de operaciones en la API Swift de OpenStack. Antes de integrar clientes API DE REST de Swift con StorageGRID, revise los detalles de la implementación para las operaciones de la cuenta, el contenedor y el objeto. 
---
= Operaciones compatibles con la API REST de Swift
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El sistema StorageGRID admite la mayoría de operaciones en la API Swift de OpenStack. Antes de integrar clientes API DE REST de Swift con StorageGRID, revise los detalles de la implementación para las operaciones de la cuenta, el contenedor y el objeto.



== Operaciones compatibles con StorageGRID

Se admiten las siguientes operaciones de API de Swift:

* xref:account-operations.adoc[Operaciones de cuentas]
* xref:container-operations.adoc[Operaciones de contenedor]
* xref:object-operations.adoc[Operaciones de objeto]




== Encabezados de respuesta comunes para todas las operaciones

El sistema StorageGRID implementa todos los encabezados comunes para las operaciones compatibles según lo definido por la API de almacenamiento de objetos Swift de OpenStack v1.

.Información relacionada
http://["OpenStack: API de almacenamiento de objetos"^]
