---
permalink: sg5600/automating-installation-configuration-appliance-nodes-configure-sga-py-script.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, automate, automating, automation, automatic, install, installation, configuration, configure, configure-sga.py script, configure-sga.py 
summary: Puede usar el script configure-sga.py para automatizar muchas de las tareas de instalación y configuración para los nodos del dispositivo StorageGRID, incluidas la instalación y configuración de un nodo de administración principal. Esta secuencia de comandos puede ser útil si tiene un gran número de dispositivos que configurar. También puede usar el script para generar un archivo JSON que contenga información de configuración del dispositivo. 
---
= Automatice la instalación y configuración de los nodos de los dispositivos con un script configure-sga.py
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `configure-sga.py` Script para automatizar muchas de las tareas de instalación y configuración para los nodos del dispositivo StorageGRID, incluida la instalación y configuración de un nodo de administración principal. Esta secuencia de comandos puede ser útil si tiene un gran número de dispositivos que configurar. También puede usar el script para generar un archivo JSON que contenga información de configuración del dispositivo.

.Lo que necesitará
* El dispositivo se ha instalado en un bastidor, conectado a las redes y encendido.
* Se han configurado los enlaces de red y las direcciones IP para el nodo de administración principal mediante el instalador de dispositivos de StorageGRID.
* Si está instalando el nodo de administrador principal, conoce su dirección IP.
* Si va a instalar y configurar otros nodos, el nodo de administrador principal se ha implementado y conoce su dirección IP.
* Para todos los nodos que no sean el nodo de administración principal, todas las subredes de red de cuadrícula que aparecen en la página Configuración de IP del instalador de dispositivos StorageGRID se han definido en la lista de subredes de redes de cuadrícula del nodo de administración principal.
* Ha descargado el `configure-sga.py` archivo. El archivo se incluye en el archivo de instalación o puede acceder a él haciendo clic en *Ayuda* > *secuencia de comandos de instalación del dispositivo* en el instalador del dispositivo StorageGRID.



NOTE: Este procedimiento es para usuarios avanzados con cierta experiencia usando interfaces de línea de comandos. También puede usar el instalador de dispositivos de StorageGRID para automatizar la configuración. +xref:automating-appliance-configuration-using-storagegrid-appliance-installer.adoc[Automatice la configuración del dispositivo con StorageGRID Appliance Installer]

.Pasos
. Inicie sesión en el equipo Linux que está utilizando para ejecutar el script Python.
. Para obtener ayuda general sobre la sintaxis de la secuencia de comandos y ver una lista de los parámetros disponibles, introduzca lo siguiente:
+
[listing]
----
configure-sga.py --help
----
+
La `configure-sga.py` el script utiliza cinco subcomandos:

+
** `advanced` Para interacciones avanzadas con dispositivos StorageGRID, incluida la configuración del BMC y la creación de un archivo JSON con la configuración actual del dispositivo
** `configure` Para configurar los parámetros de modo RAID, nombre del nodo y red
** `install` Para iniciar una instalación de StorageGRID
** `monitor` Para supervisar una instalación de StorageGRID
** `reboot` para reiniciar el dispositivo


+
Si introduce un argumento de subcomando (avanzado, configure, instale, monitor o reboot) seguido del `--help` opción usted obtendrá un texto de ayuda diferente que proporciona más detalles sobre las opciones disponibles dentro de ese subcomando: +
`configure-sga.py _subcommand_ --help`

. Para confirmar la configuración actual del nodo del dispositivo, introduzca lo siguiente donde `_SGA-install-ip_` Es cualquiera de las direcciones IP del nodo del dispositivo: +
`configure-sga.py configure _SGA-INSTALL-IP_`
+
Los resultados muestran información de IP actual del dispositivo, incluida la dirección IP del nodo de administración principal e información sobre las redes de administración, grid y cliente.

+
[listing]
----
Connecting to +https://10.224.2.30:8443+ (Checking version and connectivity.)
2021/02/25 16:25:11: Performing GET on /api/versions... Received 200
2021/02/25 16:25:11: Performing GET on /api/v2/system-info... Received 200
2021/02/25 16:25:11: Performing GET on /api/v2/admin-connection... Received 200
2021/02/25 16:25:11: Performing GET on /api/v2/link-config... Received 200
2021/02/25 16:25:11: Performing GET on /api/v2/networks... Received 200
2021/02/25 16:25:11: Performing GET on /api/v2/system-config... Received 200

  StorageGRID Appliance
    Name:        LAB-SGA-2-30
    Node type:   storage

  StorageGRID primary Admin Node
    IP:        172.16.1.170
    State:     unknown
    Message:   Initializing...
    Version:   Unknown

  Network Link Configuration
    Link Status
          Link      State      Speed (Gbps)
          ----      -----      -----
          1         Up         10
          2         Up         10
          3         Up         10
          4         Up         10
          5         Up         1
          6         Down       N/A

    Link Settings
        Port bond mode:      FIXED
        Link speed:          10GBE

        Grid Network:        ENABLED
            Bonding mode:    active-backup
            VLAN:            novlan
            MAC Addresses:   00:a0:98:59:8e:8a  00:a0:98:59:8e:82

        Admin Network:       ENABLED
            Bonding mode:    no-bond
            MAC Addresses:   00:80:e5:29:70:f4

        Client Network:      ENABLED
            Bonding mode:    active-backup
            VLAN:            novlan
            MAC Addresses:   00:a0:98:59:8e:89  00:a0:98:59:8e:81

  Grid Network
    CIDR:      172.16.2.30/21 (Static)
    MAC:       00:A0:98:59:8E:8A
    Gateway:   172.16.0.1
    Subnets:   172.17.0.0/21
               172.18.0.0/21
               192.168.0.0/21
    MTU:       1500

  Admin Network
    CIDR:      10.224.2.30/21 (Static)
    MAC:       00:80:E5:29:70:F4
    Gateway:   10.224.0.1
    Subnets:   10.0.0.0/8
               172.19.0.0/16
               172.21.0.0/16
    MTU:       1500

  Client Network
    CIDR:      47.47.2.30/21 (Static)
    MAC:       00:A0:98:59:8E:89
    Gateway:   47.47.0.1
    MTU:       2000

##############################################################
#####   If you are satisfied with this configuration,    #####
##### execute the script with the "install" sub-command. #####
##############################################################
----
. Si necesita cambiar alguno de los valores de la configuración actual, utilice `configure` subcomando para actualizarlos. Por ejemplo, si desea cambiar la dirección IP que utiliza el dispositivo para conectarse al nodo de administración principal `172.16.2.99`, introduzca lo siguiente: +
`configure-sga.py configure --admin-ip 172.16.2.99 _SGA-INSTALL-IP_`
. Si desea realizar un backup de la configuración del dispositivo en un archivo JSON, utilice `advanced` y.. `backup-file` subcomandos. Por ejemplo, si desea realizar una copia de seguridad de la configuración de un dispositivo con dirección IP `_SGA-INSTALL-IP_` a un archivo llamado `appliance-SG1000.json`, introduzca lo siguiente: +
`configure-sga.py advanced --backup-file appliance-SG1000.json _SGA-INSTALL-IP_`
+
El archivo JSON que contiene la información de configuración se escribe en el mismo directorio desde el que se ejecutó la secuencia de comandos.

+

IMPORTANT: Compruebe que el nombre del nodo de nivel superior del archivo JSON generado coincida con el nombre del dispositivo. No haga ningún cambio en este archivo a menos que sea un usuario con experiencia y que tenga una profunda comprensión de las API de StorageGRID.

. Cuando esté satisfecho con la configuración del dispositivo, utilice `install` y.. `monitor` subcomandos para instalar el dispositivo: +
`configure-sga.py install --monitor _SGA-INSTALL-IP_`
. Si desea reiniciar el dispositivo, introduzca lo siguiente: +
`configure-sga.py reboot _SGA-INSTALL-IP_`

