---
permalink: sg5600/preparing-site-sg5600.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, install, installation, site prep, site preparating, preparing site, site requirements, requirements, site, dimensions, weight, weights, temperature, humidity, altitude, airflow, heat, wiring, power, grounding, facility 
summary: Antes de instalar el dispositivo, debe asegurarse de que el sitio y el armario o rack que desee usar cumplan con las especificaciones de un dispositivo StorageGRID. 
---
= Preparar el sitio (SG5600)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar el dispositivo, debe asegurarse de que el sitio y el armario o rack que desee usar cumplan con las especificaciones de un dispositivo StorageGRID.

.Pasos
. Confirmar que el emplazamiento cumple los requisitos de temperatura, humedad, rango de altitud, flujo de aire, disipación de calor, cableado, alimentación y conexión a tierra. Si desea obtener más información, consulte Hardware Universe de NetApp.
. Obtenga un armario o rack de 19 pulgadas (48.3 cm) para colocar bandejas de este tamaño (sin cables):
+
|===
| Modelo de dispositivo | Altura | Anchura | Profundidad | Peso máximo 


 a| 
SG5612

(12 unidades)
 a| 
3.40 pda

(8.64 cm)
 a| 
19.0 pda

(48.26 cm)
 a| 
21.75 pda

(55.25 cm)
 a| 
59.5 lb

(27 kg)



 a| 
SG5660

(60 unidades)
 a| 
7.00 pda

(17.78 cm)
 a| 
17.75 pda

(45.08 cm)
 a| 
32.50 pda

(82.55 cm)
 a| 
236.2 lb.

(107.1 kg)

|===
. Instale los switches de red necesarios. Consulte la herramienta de la matriz de interoperabilidad de NetApp para obtener información de compatibilidad.


.Información relacionada
https://hwu.netapp.com["Hardware Universe de NetApp"^]

https://mysupport.netapp.com/NOW/products/interoperability["Interoperabilidad de NetApp"^]
