---
permalink: sg5600/replacing-other-hardware-components-sg5600.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, Replacing, replace, hardware, components, remove, removing, removal, install, installing, installation, drive, fan, power supply, battery 
summary: Es posible que deba sustituir una unidad, un ventilador, una fuente de alimentación o una batería en el dispositivo StorageGRID. 
---
= Sustituir otros componentes de hardware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que deba sustituir una unidad, un ventilador, una fuente de alimentación o una batería en el dispositivo StorageGRID.

.Lo que necesitará
* Tiene el procedimiento de sustitución del hardware E-Series.
* El aparato se ha estado xref:placing-appliance-into-maintenance-mode.adoc[se pone en modo de mantenimiento] si el procedimiento de sustitución de componentes requiere que apague el aparato.


.Acerca de esta tarea
Para sustituir una unidad, un contenedor de alimentación/ventilador, un contenedor de ventilador, un contenedor de alimentación, una batería, O el cajón de unidades, consulte los procedimientos estándar de las cabinas de almacenamiento E2700 y E5600. Céntrese en las instrucciones paso a paso para extraer y sustituir el hardware en sí; muchos de los procedimientos de Administrador de almacenamiento de SANtricity no se aplican a un dispositivo.



== Instrucciones de sustitución de componentes de SG5612

|===
| FRU | Consulte 


 a| 
Unidad
 a| 
Siga los pasos de las instrucciones E-Series para reemplazar una unidad en los soportes de 12 o 24 unidades E2600, E2700, E5400, E5500, E5600.



 a| 
Contenedor de alimentación/ventilador
 a| 
Siga los pasos de las instrucciones de E-Series para reemplazar una batería de alimentación/ventilador con error en el soporte de controladoras E5612 o E5624



 a| 
Batería en la controladora E2700 (requiere la extracción de la controladora)
 a| 
Siga los pasos de xref:replacing-e2700-controller.adoc[Sustituya la controladora E2700], pero instale la batería nueva en el controlador existente.

|===


== Instrucciones para la sustitución de componentes SG5660

|===
| FRU | Consulte 


 a| 
Unidad
 a| 
Siga los pasos de las instrucciones E-Series para reemplazar una unidad en las bandejas E2660, E2760, E5460, E5560 o E5660.



 a| 
Contenedor de alimentación
 a| 
Siga los pasos de las instrucciones de E-Series para reemplazar un contenedor de alimentación con error en el soporte de controladoras E5660



 a| 
Contenedor de ventilador
 a| 
Siga los pasos de las instrucciones de E-Series para reemplazar un contenedor de ventilador con error en el soporte de controladoras E5660



 a| 
Batería en la controladora E2700 (requiere la extracción de la controladora)
 a| 
Siga los pasos de xref:replacing-e2700-controller.adoc[Sustituya la controladora E2700], pero instale la batería nueva en el controlador existente.

|===
.Información relacionada
https://mysupport.netapp.com/info/web/ECMP11751516.html["Procedimientos para reemplazar hardware E-Series y EF-Series de NetApp"^]

http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61765["Documentación de NetApp: Serie E2700"^]

http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61893["Documentación de NetApp: Serie E5600"^]
