---
permalink: tenant/changing-consistency-level.html 
sidebar: sidebar 
keywords: how to change tenant consistency level, read after new write, read-after-new-write, strong site, strong-site, strong global, strong-global 
summary: Si usa un inquilino de S3, puede usar el administrador de inquilinos o la API de gestión de inquilinos para cambiar el control de coherencia para las operaciones realizadas en los objetos en los bloques S3. 
---
= Cambie el nivel de coherencia
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si usa un inquilino de S3, puede usar el administrador de inquilinos o la API de gestión de inquilinos para cambiar el control de coherencia para las operaciones realizadas en los objetos en los bloques S3.

.Lo que necesitará
* Debe iniciar sesión en el administrador de inquilinos mediante un xref:../admin/web-browser-requirements.adoc[navegador web compatible].
* Debe pertenecer a un grupo de usuarios que tenga el permiso Administrar todos los cucharones o acceso raíz. Estos permisos anulan la configuración de los permisos en las políticas de grupo o bloque. Consulte xref:tenant-management-permissions.adoc[Permisos de gestión de inquilinos].


.Acerca de esta tarea
El nivel de consistencia proporciona un equilibrio entre la disponibilidad de los objetos y la coherencia de dichos objetos en distintos nodos de almacenamiento y sitios. En general, debe utilizar el nivel de consistencia de *lectura tras escritura nueva* para sus cucharones.

Si el nivel de consistencia de *lectura tras escritura nueva* no cumple los requisitos de la aplicación cliente, puede cambiar el nivel de consistencia estableciendo el nivel de consistencia de la cuchara o utilizando la `Consistency-Control` encabezado. La `Consistency-Control` el encabezado anula el nivel de consistencia del cucharón.


NOTE: Cuando se cambia el nivel de consistencia de un cubo, solo se garantiza que los objetos que se ingieren después del cambio alcancen el nivel revisado.

.Pasos
. Seleccione *ALMACENAMIENTO (S3)* > *Cuchos*.
. Seleccione el nombre del bloque de la lista.
+
Aparece la página de detalles bucket.

. Seleccione *Opciones de bloque* > *nivel de coherencia*.
. Seleccione un nivel de coherencia para las operaciones realizadas en los objetos de este bloque.
+
** *Todo*: Proporciona el más alto nivel de consistencia. Todos los nodos reciben los datos inmediatamente o se produce un error en la solicitud.
** *Strong-global*: Garantiza la consistencia de lectura tras escritura para todas las solicitudes de los clientes en todos los sitios.
** *Strong-site*: Garantiza la consistencia de lectura después de escritura para todas las solicitudes de los clientes dentro de un sitio.
** *Read-after-new-write* (por defecto): Proporciona consistencia de lectura después de escritura para nuevos objetos y consistencia eventual para las actualizaciones de objetos. Ofrece garantías de alta disponibilidad y protección de datos. Recomendado para la mayoría de los casos.
** *Disponible*: Proporciona consistencia eventual tanto para nuevos objetos como para actualizaciones de objetos. Para los depósitos S3, utilice sólo según sea necesario (por ejemplo, para un depósito que contiene valores de log que rara vez se leen, o para operaciones HEAD u GET en claves que no existen). No se admite para bloques de FabricPool S3.


. Seleccione *Guardar cambios*.

