---
permalink: tenant/index.html 
sidebar: sidebar 
keywords: use tenant account 
summary: 'Una cuenta de inquilino permite usar la API DE REST de simple Storage Service (S3) o la API DE REST de Swift para almacenar y recuperar objetos en un sistema StorageGRID.' 
---
= Usar una cuenta de inquilino: Descripción general
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una cuenta de inquilino permite usar la API DE REST de simple Storage Service (S3) o la API DE REST de Swift para almacenar y recuperar objetos en un sistema StorageGRID.



== ¿Qué es una cuenta de inquilino?

Cada cuenta de inquilino tiene sus propios grupos locales o federados, usuarios, bloques S3 o contenedores Swift, y objetos.

Opcionalmente, las cuentas de arrendatarios se pueden utilizar para segregar objetos almacenados por diferentes entidades. Por ejemplo, pueden utilizarse varias cuentas de inquilino en cualquiera de estos casos de uso:

* *Caso de uso empresarial:* Si el sistema StorageGRID se está utilizando dentro de una empresa, el almacenamiento de objetos de la cuadrícula puede estar segregado por los diferentes departamentos de la organización. Por ejemplo, puede haber cuentas de inquilino para el departamento de marketing, el departamento de soporte al cliente, el departamento de recursos humanos, etc.
+

NOTE: Si utiliza el protocolo cliente S3, también puede utilizar bloques S3 y políticas de bucket para separar objetos entre los departamentos de una empresa. No es necesario crear cuentas de arrendatario independientes. Consulte xref:../s3/index.adoc[Instrucciones para implementar aplicaciones cliente de S3].

* *Caso de uso del proveedor de servicios:* Si un proveedor de servicios utiliza el sistema StorageGRID, el almacenamiento de objetos de la cuadrícula puede estar segregado por las diferentes entidades que arriendan el almacenamiento. Por ejemplo, puede que haya cuentas de inquilino para la empresa A, la empresa B, la empresa C, etc.




== Cómo crear una cuenta de inquilino

Las cuentas de inquilino se crean mediante una xref:../admin/managing-tenants.adoc[El administrador de grid de StorageGRID que utiliza Grid Manager]. Al crear una cuenta de inquilino, el administrador de grid especifica la siguiente información:

* Nombre para mostrar del arrendatario (el ID de cuenta del arrendatario se asigna automáticamente y no se puede modificar).
* Si la cuenta de inquilino usa S3 o Swift.
* Para las cuentas de inquilino de S3: Si la cuenta de inquilino está permitida para usar los servicios de la plataforma. Si se permite el uso de servicios de plataforma, la cuadrícula debe configurarse para que admita su uso.
* Opcionalmente, una cuota de almacenamiento para la cuenta de inquilino: El número máximo de gigabytes, terabytes o petabytes disponibles para los objetos del inquilino. La cuota de almacenamiento de un inquilino representa una cantidad lógica (tamaño de objeto), no una cantidad física (tamaño en disco).
* Si está habilitada la federación de identidades para el sistema StorageGRID, el grupo federado tiene permiso de acceso raíz para configurar la cuenta de inquilino.
* Si el sistema StorageGRID no utiliza el inicio de sesión único (SSO), tanto si la cuenta de inquilino usará su propio origen de identidad como si comparte el origen de identidad de la cuadrícula, así como la contraseña inicial del usuario raíz local del inquilino.


Además, los administradores de grid pueden habilitar la configuración de bloqueo de objetos de S3 para el sistema StorageGRID si las cuentas de inquilinos S3 necesitan cumplir con los requisitos normativos. Cuando se habilita el bloqueo de objetos S3, todas las cuentas de inquilinos S3 pueden crear y gestionar bloques conforme a la normativa.



=== Configure los inquilinos S3

Después de un xref:../admin/creating-tenant-account.adoc[Se crea la cuenta de inquilino de S3], Puede acceder al Administrador de arrendatarios para realizar tareas como las siguientes:

* Configurar la federación de identidades (a menos que el origen de identidades se comparta con la cuadrícula) o crear grupos y usuarios locales
* Gestión de claves de acceso de S3
* Creación y gestión de bloques de S3, incluidos los bloques conformes a la normativa
* Uso de servicios de plataforma (si está activado)
* Supervisión del uso de almacenamiento



IMPORTANT: Aunque puede crear y gestionar bloques de S3 con el administrador de inquilinos, debe tener xref:../s3/index.adoc[Las claves de acceso S3 y use la API DE REST de S3 para procesar y gestionar objetos].



=== Configure los inquilinos Swift

Después de un xref:../admin/creating-tenant-account.adoc[Se crea la cuenta de inquilino de Swift], Puede acceder al Administrador de arrendatarios para realizar tareas como las siguientes:

* Configurar la federación de identidades (a menos que el origen de identidades se comparta con la cuadrícula) y crear grupos y usuarios locales
* Supervisión del uso de almacenamiento



IMPORTANT: Los usuarios de Swift deben tener el permiso acceso raíz para acceder al Administrador de inquilinos. Sin embargo, el permiso acceso raíz no permite a los usuarios autenticarse en el xref:../swift/index.adoc[API REST de Swift] para crear contenedores y objetos de procesamiento. Los usuarios deben tener el permiso de administrador de Swift para autenticarse en la API DE REST de Swift.



== Utilice el Administrador de arrendatarios

El Administrador de inquilinos le permite gestionar todos los aspectos de una cuenta de inquilino de StorageGRID.

Puede usar el Administrador de inquilinos para supervisar el uso del almacenamiento de una cuenta de inquilino y para gestionar los usuarios con federación de identidades o creando grupos y usuarios locales. En las cuentas de inquilinos S3, también se pueden gestionar claves S3, gestionar bloques S3 y configurar servicios de plataforma.
