---
permalink: tenant/using-search-integration-service.html 
sidebar: sidebar 
keywords: how to use search integration service 
summary: El servicio de integración de búsqueda es uno de los tres servicios de la plataforma StorageGRID. Este servicio puede habilitar el envío de metadatos de objetos a un índice de búsqueda de destino siempre que se cree, se elimine o actualice los metadatos o las etiquetas de un objeto. 
---
= Utilice el servicio de integración de búsqueda
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El servicio de integración de búsqueda es uno de los tres servicios de la plataforma StorageGRID. Este servicio puede habilitar el envío de metadatos de objetos a un índice de búsqueda de destino siempre que se cree, se elimine o actualice los metadatos o las etiquetas de un objeto.

Puede configurar la integración de búsqueda mediante el Administrador de inquilinos para aplicar XML de configuración de StorageGRID personalizado a un bloque.


NOTE: Debido a que el servicio de integración de búsqueda hace que los metadatos de objeto se envíen a un destino, su XML de configuración se denomina XML_ de configuración de notificación de metadatos. Este XML de configuración es diferente al _notification Configuration XML_ utilizado para habilitar las notificaciones de eventos.

Consulte xref:../s3/index.adoc[Instrucciones para implementar aplicaciones cliente de S3] Para obtener detalles sobre las siguientes operaciones personalizadas de la API de REST de StorageGRID S3:

* DELETE bucket metadata notification Configuration
* OBTENGA la solicitud de configuración de notificación de metadatos del bloque
* PUT bucket metadata notification Configuration


.Información relacionada
xref:configuration-xml-for-search-configuration.adoc[XML de configuración para la integración de búsqueda]

xref:object-metadata-included-in-metadata-notifications.adoc[Metadatos de objetos incluidos en las notificaciones de metadatos]

xref:json-generated-by-search-integration-service.adoc[JSON generado por el servicio de integración de búsqueda]

xref:configuring-search-integration-service.adoc[Configure el servicio de integración de búsqueda]

xref:../s3/index.adoc[Use S3]
