---
permalink: vmware/required-materials.html 
sidebar: sidebar 
keywords: installation materials vmware 
summary: Antes de instalar StorageGRID, debe recopilar y preparar los materiales necesarios. 
---
= Materiales requeridos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar StorageGRID, debe recopilar y preparar los materiales necesarios.

[cols="1a,2a"]
|===
| Elemento | Notas 


 a| 
Licencia de StorageGRID de NetApp
 a| 
Debe tener una licencia de NetApp válida y con firma digital.

*Nota*: El archivo de instalación de StorageGRID incluye una licencia gratuita que no proporciona ningún derecho de asistencia para el producto.



 a| 
Archivo de instalación de StorageGRID
 a| 
Debe xref:downloading-and-extracting-storagegrid-installation-files.adoc[Descargue el archivo de instalación de StorageGRID y extraiga los archivos].



 a| 
Software y documentación de VMware
 a| 
Durante la instalación, se usa VMware vSphere Web Client para implementar nodos de grid virtual en máquinas virtuales. Para las versiones compatibles, consulte la matriz de interoperabilidad.



 a| 
Portátil de servicio
 a| 
El sistema StorageGRID se instala mediante un laptop de mantenimiento.el portátil de servicio debe tener:

* Puerto de red
* Cliente SSH (por ejemplo, PuTTY)
* xref:../admin/web-browser-requirements.adoc[Navegador web compatible]




 a| 
Documentación de StorageGRID
 a| 
* xref:../release-notes/index.adoc[Notas de la versión]
* xref:../admin/index.adoc[Instrucciones para administrar StorageGRID]


|===
.Información relacionada
https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^]
