---
permalink: vmware/troubleshooting-installation-issues.html 
sidebar: sidebar 
keywords: how to troubleshoot installation issues 
summary: Si se produce algún problema durante la instalación del sistema StorageGRID, puede acceder a los archivos de registro de la instalación. 
---
= Solucionar problemas de instalación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si se produce algún problema durante la instalación del sistema StorageGRID, puede acceder a los archivos de registro de la instalación.

A continuación se muestran los archivos de registro de la instalación principales, que el soporte técnico puede necesitar para resolver problemas.

* `/var/local/log/install.log` (se encuentra en todos los nodos de grid)
* `/var/local/log/gdu-server.log` (Encontrado en el nodo de administración principal)


Para obtener más información sobre cómo acceder a los archivos de registro, consulte xref:../monitor/index.adoc[Instrucciones para la supervisión y resolución de problemas de StorageGRID]. Para obtener ayuda sobre la solución de problemas de instalación del dispositivo, consulte las instrucciones de instalación y mantenimiento de los dispositivos. Si necesita ayuda adicional, póngase en contacto con el soporte técnico.

xref:../sg100-1000/index.adoc[Servicios de aplicaciones SG100 y SG1000]

xref:../sg6000/index.adoc[Dispositivos de almacenamiento SG6000]

xref:../sg5700/index.adoc[Dispositivos de almacenamiento SG5700]

xref:../sg5600/index.adoc[Dispositivos de almacenamiento SG5600]

https://["Soporte de NetApp"^]



== La reserva de recursos de la máquina virtual requiere ajustes

Los archivos OVF incluyen una reserva de recursos diseñada para garantizar que cada nodo de grid tiene suficiente RAM y CPU para funcionar de forma eficiente. Si crea máquinas virtuales implementando estos archivos OVF en VMware y el número predefinido de recursos no está disponible, las máquinas virtuales no se iniciarán.

.Acerca de esta tarea
Si tiene la seguridad de que el host de máquina virtual tiene suficientes recursos para cada nodo de grid, ajuste manualmente los recursos asignados para cada máquina virtual e intente iniciar las máquinas virtuales.

.Pasos
. En el árbol del cliente del hipervisor de VMware vSphere, seleccione la máquina virtual que no se ha iniciado.
. Haga clic con el botón secundario‐en la máquina virtual y seleccione *Editar configuración*.
. En la ventana Propiedades de máquinas virtuales, seleccione la ficha *Recursos*.
. Ajuste los recursos asignados a la máquina virtual:
+
.. Seleccione *CPU* y, a continuación, utilice el control deslizante Reservación para ajustar el MHz reservado para esta máquina virtual.
.. Seleccione *memoria* y, a continuación, utilice el control deslizante Reservación para ajustar el MB reservado para esta máquina virtual.


. Haga clic en *Aceptar*.
. Repita esto según sea necesario para otras máquinas virtuales alojadas en el mismo host de VM.

