---
permalink: rhel/planning-and-preparation.html 
sidebar: sidebar 
keywords: installation planning red hat linux 
summary: Antes de implementar nodos de grid y configurar la cuadrícula de StorageGRID, debe estar familiarizado con los pasos y los requisitos para completar el procedimiento. 
---
= Antes de instalar (Red Hat o CentOS)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de implementar nodos de grid y configurar la cuadrícula de StorageGRID, debe estar familiarizado con los pasos y los requisitos para completar el procedimiento.

Los procedimientos de puesta en marcha y configuración de StorageGRID dan por sentado que está familiarizado con la arquitectura y el funcionamiento del sistema StorageGRID.

Puede implementar un solo sitio o varios sitios a la vez; sin embargo, todos los sitios deben cumplir con el requisito mínimo de tener al menos tres nodos de almacenamiento.

Antes de iniciar una instalación de StorageGRID, debe:

* Comprenda los requisitos de computación de StorageGRID, incluidos los requisitos mínimos de CPU y RAM para cada nodo.
* Comprenda cómo StorageGRID admite varias redes para la separación del tráfico, la seguridad y la comodidad administrativa. Además, tenga un plan para qué redes piensa conectar a cada nodo StorageGRID.
+
Consulte las directrices para redes de StorageGRID.

* Comprenda los requisitos de almacenamiento y rendimiento de cada tipo de nodo de grid.
* Identificar un conjunto de servidores (físicos, virtuales o ambos) que, agregado, proporcione los recursos suficientes para respaldar el número y el tipo de nodos de StorageGRID que va a implementar.
* Comprenda los requisitos para la migración de nodos si desea realizar tareas de mantenimiento programadas en hosts físicos sin ninguna interrupción del servicio.
* Recopile toda la información de la red con antelación. A menos que utilice DHCP, recopile las direcciones IP para asignar a cada nodo de grid y las direcciones IP de los servidores del sistema de nombres de dominio (DNS) y del protocolo de hora de red (NTP) que se utilizarán.
* Instale, conecte y configure todo el hardware necesario, incluidos los dispositivos StorageGRID, según las especificaciones.
+

NOTE: El procedimiento de instalación de StorageGRID no incluye las instrucciones de instalación e integración específicas de hardware. Para aprender a instalar dispositivos StorageGRID, consulte las instrucciones de instalación y mantenimiento del dispositivo.

* Decida qué herramientas de implementación y configuración disponibles desea utilizar.


.Información relacionada
xref:../network/index.adoc[Directrices sobre redes]

xref:../sg100-1000/index.adoc[Servicios de aplicaciones SG100 y SG1000]

xref:../sg6000/index.adoc[Dispositivos de almacenamiento SG6000]

xref:../sg5700/index.adoc[Dispositivos de almacenamiento SG5700]

xref:../sg5600/index.adoc[Dispositivos de almacenamiento SG5600]
