---
permalink: rhel/troubleshooting-installation-issues.html 
sidebar: sidebar 
keywords: how to troubleshoot red hat linux centos installation 
summary: Si se produce algún problema durante la instalación del sistema StorageGRID, puede acceder a los archivos de registro de la instalación. Es posible que el soporte técnico también deba utilizar los archivos de registro de instalación para resolver problemas. 
---
= Solucionar problemas de instalación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si se produce algún problema durante la instalación del sistema StorageGRID, puede acceder a los archivos de registro de la instalación. Es posible que el soporte técnico también deba utilizar los archivos de registro de instalación para resolver problemas.

Los siguientes archivos de registro de instalación están disponibles en el contenedor que ejecuta cada nodo:

* `/var/local/log/install.log` (se encuentra en todos los nodos de grid)
* `/var/local/log/gdu-server.log` (Encontrado en el nodo de administración principal)


Los siguientes archivos de registro de instalación están disponibles en el host:

* `/var/log/storagegrid/daemon.log`
* `/var/log/storagegrid/nodes/node-name.log`


Para obtener más información sobre cómo acceder a los archivos de registro, consulte las instrucciones para supervisar y solucionar problemas de StorageGRID. Para obtener ayuda sobre la solución de problemas de instalación del dispositivo, consulte las instrucciones de instalación y mantenimiento de los dispositivos. Si necesita ayuda adicional, póngase en contacto con el soporte técnico.

.Información relacionada
xref:../monitor/index.adoc[Supervisión y solución de problemas]

xref:../sg100-1000/index.adoc[Servicios de aplicaciones SG100 y SG1000]

xref:../sg6000/index.adoc[Dispositivos de almacenamiento SG6000]

xref:../sg5700/index.adoc[Dispositivos de almacenamiento SG5700]

xref:../sg5600/index.adoc[Dispositivos de almacenamiento SG5600]

https://mysupport.netapp.com/site/global/dashboard["Soporte de NetApp"^]
