---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: Cada nodo de su grid tiene una contraseña de consola de nodo única, que necesita iniciar sesión en el nodo. Use estos pasos para cambiar la contraseña de la consola de nodos de cada nodo de la cuadrícula. Las contraseñas se almacenan en el paquete de recuperación. 
---
= Cambie las contraseñas de la consola de los nodos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada nodo de su grid tiene una contraseña de consola de nodo única, que necesita iniciar sesión en el nodo. Siga estos pasos para cambiar cada contraseña de la consola de nodos única para cada nodo de la cuadrícula.

.Lo que necesitará
* Ha iniciado sesión en Grid Manager mediante un link:../admin/web-browser-requirements.html["navegador web compatible"].
* Tiene el permiso de mantenimiento o acceso raíz.
* Tiene la clave de acceso de aprovisionamiento actual.


.Acerca de esta tarea
Utilice la contraseña de la consola del nodo para iniciar sesión en un nodo como “admin” mediante SSH o en el usuario root en una conexión de la consola física/VM. El proceso de cambiar la contraseña de la consola del nodo crea nuevas contraseñas para cada nodo de la cuadrícula y almacena las contraseñas en una actualización `Passwords.txt` En el paquete de recuperación. Las contraseñas figuran en la columna Password de la `Passwords.txt` archivo.


NOTE: Hay contraseñas de acceso SSH separadas para las claves SSH que se usan para la comunicación entre nodos. Este procedimiento no cambia las contraseñas de acceso SSH.



== Acceda al asistente

.Pasos
. Seleccione *CONFIGURACIÓN* > *Control de acceso* > *contraseñas de cuadrícula*.
. En *Cambiar contraseñas de consola de nodo*, selecciona *Hacer un cambio*.




== Introduzca la clave de acceso de aprovisionamiento

.Pasos
. Introduzca la clave de acceso de aprovisionamiento para el grid.
. Seleccione *continuar*.




== [[download-current]]Descargue el paquete de recuperación actual

Antes de cambiar las contraseñas de la consola de nodos, descargue el paquete de recuperación actual. Puede usar las contraseñas de este archivo si el proceso de cambio de contraseña falla en cualquier nodo.

.Pasos
. Seleccione *Descargar paquete de recuperación*.
. Copie el archivo del paquete de recuperación (`.zip`) a dos ubicaciones seguras, seguras y separadas.
+

CAUTION: El archivo del paquete de recuperación debe estar protegido porque contiene claves de cifrado y contraseñas que se pueden usar para obtener datos del sistema StorageGRID.

. Seleccione *continuar*.
. Cuando aparezca el cuadro de diálogo de confirmación, seleccione *Sí* si está listo para empezar a cambiar las contraseñas de la consola del nodo.
+
No puede cancelar este proceso una vez que se inicia.





== Cambie las contraseñas de la consola de los nodos

Cuando se inicia el proceso de contraseña de la consola del nodo, se genera un nuevo paquete de recuperación que incluye las nuevas contraseñas. A continuación, las contraseñas se actualizan en cada nodo.

.Pasos
. Espere a que se genere el nuevo paquete de recuperación, lo que puede tardar unos minutos.
. Seleccione *Descargar nuevo paquete de recuperación*.
. Cuando finalice la descarga:
+
.. Abra el `.zip` archivo.
.. Confirme que puede acceder al contenido, incluido el `Passwords.txt` archivo, que contiene las nuevas contraseñas de la consola del nodo.
.. Copie el nuevo archivo de Recovery Package (`.zip`) a dos ubicaciones seguras, seguras y separadas.
+

CAUTION: No sobrescriba el paquete de recuperación antiguo.

+
El archivo del paquete de recuperación debe estar protegido porque contiene claves de cifrado y contraseñas que se pueden usar para obtener datos del sistema StorageGRID.



. Active la casilla de verificación para indicar que ha descargado el nuevo paquete de recuperación y que ha verificado el contenido.
. Seleccione *Cambiar contraseñas de consola de nodos* y espere a que todos los nodos se actualicen con las nuevas contraseñas. Esto puede tardar varios minutos.
+
Si se modifican contraseñas para todos los nodos, se muestra un banner verde de éxito. Vaya al paso siguiente.

+
Si se produce un error durante el proceso de actualización, un mensaje de banner enumera la cantidad de nodos que no pudieron cambiar sus contraseñas. El sistema volverá a intentar automáticamente el proceso en cualquier nodo que no haya cambiado su contraseña. Si el proceso finaliza con algunos nodos que aún no han cambiado la contraseña, aparece el botón *Reintentar*.

+
Si la actualización de la contraseña falló para uno o más nodos:

+
.. Revise los mensajes de error que aparecen en la tabla.
.. Resuelva los problemas.
.. Seleccione *Reintentar*.
+

NOTE: Al volver a intentar solo se cambian las contraseñas de la consola de nodos en los nodos que fallaron durante los intentos anteriores de cambio de contraseña.



. Después de cambiar las contraseñas de la consola de nodos para todos los nodos, elimine el <<download-current,Primer paquete de recuperación descargado>>.
. Opcionalmente, utilice el enlace *paquete de recuperación* para descargar una copia adicional del nuevo paquete de recuperación.

