---
permalink: admin/configuring-storagegrid-certificates-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricpool, ONTAP certificates 
summary: En el caso de clientes S3 que realizan una validación de nombre de host estricta y no admiten la deshabilitación de la validación estricta de nombre de host, como clientes ONTAP que utilizan FabricPool, puede generar o cargar un certificado de servidor al configurar el extremo del equilibrador de carga. 
---
= Configure los certificados StorageGRID para FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En el caso de clientes S3 que realizan una validación de nombre de host estricta y no admiten la deshabilitación de la validación estricta de nombre de host, como clientes ONTAP que utilizan FabricPool, puede generar o cargar un certificado de servidor al configurar el extremo del equilibrador de carga.

.Lo que necesitará
* Tiene permisos de acceso específicos.
* Ha iniciado sesión en Grid Manager mediante un xref:../admin/web-browser-requirements.adoc[navegador web compatible].


.Acerca de esta tarea
Al crear un extremo de equilibrador de carga, se puede generar un certificado de servidor autofirmado o cargar un certificado firmado por una entidad de certificación (CA) conocida. En los entornos de producción, se debe utilizar un certificado firmado por una CA conocida. Los certificados firmados por una CA se pueden rotar de forma no disruptiva. También son más seguros porque ofrecen una mejor protección contra los ataques de tipo "hombre en el medio".

En los siguientes pasos, se ofrecen directrices generales para clientes S3 que usan FabricPool. Para obtener información más detallada y procedimientos, consulte xref:../fabricpool/index.adoc[Configure StorageGRID para FabricPool].


NOTE: El servicio de equilibrador de carga de conexión (CLB) independiente en los nodos de puerta de enlace queda obsoleto y no se recomienda su uso con FabricPool.

.Pasos
. Opcionalmente, configure un grupo de alta disponibilidad (ha) para que lo utilice FabricPool.
. Cree un extremo de equilibrador de carga de S3 para que se utilice FabricPool.
+
Cuando crea un extremo de equilibrio de carga HTTPS, se le solicita que cargue el certificado de servidor, la clave privada de certificado y el paquete de CA opcional.

. Adjuntar StorageGRID como nivel de cloud en ONTAP.
+
Especifique el puerto de extremo de equilibrio de carga y el nombre de dominio completo utilizado en el certificado de CA que ha cargado. A continuación, proporcione el certificado de CA.

+

NOTE: Si una CA intermedia emitió el certificado StorageGRID, debe proporcionar el certificado de CA intermedio. Si la CA raíz emitió directamente el certificado StorageGRID, debe proporcionar el certificado de CA raíz.


