---
permalink: admin/managing-traffic-classification-policies.html 
sidebar: sidebar 
keywords: qos, quality of service, traffic classification, best practices, limit traffic, monitor traffic 
summary: 'Para mejorar sus ofertas de calidad de servicio \(QoS\), puede crear directivas de clasificación del tráfico para identificar y supervisar distintos tipos de tráfico de red. Estas políticas pueden ayudar a limitar y supervisar el tráfico.' 
---
= Administrar directivas de clasificación de tráfico
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para mejorar sus ofertas de calidad de servicio (QoS), puede crear normativas de clasificación del tráfico para identificar y supervisar distintos tipos de tráfico de red. Estas políticas pueden ayudar a limitar y supervisar el tráfico.

Las políticas de clasificación del tráfico se aplican a los extremos en el servicio StorageGRID Load Balancer para los nodos de puerta de enlace y los nodos de administración. Para crear directivas de clasificación de tráfico, debe haber creado ya puntos finales de equilibrador de carga.



== Haga coincidir las reglas y los límites opcionales

Cada directiva de clasificación de tráfico contiene una o más reglas coincidentes para identificar el tráfico de red relacionado con una o varias de las siguientes entidades:

* Cucharones
* Clientes
* Subredes (subredes IPv4 que contienen al cliente)
* Puntos finales (puntos finales del equilibrador de carga)


StorageGRID supervisa el tráfico que coincide con cualquier regla dentro de la política de acuerdo con los objetivos de la regla. Cualquier tráfico que coincida con cualquier regla de una directiva se gestiona mediante dicha directiva. A la inversa, puede establecer reglas que coincidan con todo el tráfico excepto una entidad especificada.

Opcionalmente, puede establecer límites para una directiva en función de los siguientes parámetros:

* Ancho de banda del agregado en
* Ancho de banda del agregado agotado
* Solicitudes de lectura simultáneas
* Solicitudes de escritura simultáneas
* Ancho de banda por solicitud en
* Ancho de banda por solicitud agotado
* Tasa de solicitud de lectura
* Tasa de solicitudes de escritura



NOTE: Puede crear políticas para limitar el ancho de banda agregado o para limitar el ancho de banda por solicitud. Sin embargo, StorageGRID no puede limitar ambos tipos de ancho de banda a la vez. Los límites de ancho de banda agregados pueden imponer un impacto adicional mínimo en el rendimiento en el tráfico no limitado.



== Limitación del tráfico

Cuando ha creado directivas de clasificación de tráfico, el tráfico se puede limitar según el tipo de reglas y límites establecidos. Para límites de ancho de banda agregados o por solicitud, las solicitudes se transmiten de entrada o salida a la velocidad establecida. StorageGRID sólo puede aplicar una velocidad, por lo que la política más específica, por tipo de matrcher, es la aplicada. Para todos los demás tipos de límites, las solicitudes de clientes se retrasan 250 milisegundos y reciben una respuesta de reducción lenta de 503 para las solicitudes que exceden cualquier límite de directiva coincidente.

En Grid Manager, puede ver los gráficos de tráfico y comprobar que las directivas están aplicando los límites de tráfico que espera.



== Utilice las políticas de clasificación del tráfico con los SLA

Puede utilizar políticas de clasificación del tráfico junto con los límites de capacidad y protección de datos para aplicar acuerdos de nivel de servicio (SLA) que ofrezcan detalles sobre la capacidad, la protección de datos y el rendimiento.

Los límites de clasificación del tráfico se implementan por equilibrador de carga. Si el tráfico se distribuye de forma simultánea entre varios equilibradores de carga, las tasas máximas totales son un múltiplo de los límites de velocidad que especifique.

El siguiente ejemplo muestra tres niveles de un acuerdo de nivel de servicio. Puede crear políticas de clasificación del tráfico para alcanzar los objetivos de rendimiento de cada nivel de SLA.

[cols="1a,1a,1a,1a,1a"]
|===
| Nivel de servicio | Capacidad | Protección de datos | Rendimiento | Coste 


 a| 
Oro
 a| 
1 PB de almacenamiento permitido
 a| 
Regla de 3 copia de ILM
 a| 
25 000 solicitudes/s

Ancho de banda de 5 GB/s (40 Gbps)
 a| 
$$$$ por mes



 a| 
Plata
 a| 
Capacidad de almacenamiento de 250 TB
 a| 
2 regla de copia de ILM
 a| 
10 000 solicitudes/s

Ancho de banda de 1.25 GB/s (10 Gbps)
 a| 
$$ al mes



 a| 
Bronce
 a| 
Capacidad de almacenamiento de 100 TB
 a| 
2 regla de copia de ILM
 a| 
5 000 solicitudes/s

Ancho de banda de 1 GB/s (8 Gbps)
 a| 
$ al mes

|===