---
permalink: admin/reviewing-storagegrid-encryption-methods.html 
sidebar: sidebar 
keywords: encryption, encrypting data, best practices 
summary: StorageGRID proporciona una serie de opciones para cifrar datos. Debe revisar los métodos disponibles para determinar qué métodos cumplen sus requisitos de protección de datos. 
---
= Consulte los métodos de cifrado de StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID proporciona una serie de opciones para cifrar datos. Debe revisar los métodos disponibles para determinar qué métodos cumplen sus requisitos de protección de datos.

La tabla proporciona un resumen de alto nivel de los métodos de cifrado disponibles en StorageGRID.

[cols="1a,1a,1a"]
|===
| Opción de cifrado | Cómo funciona | Se aplica a. 


 a| 
Servidor de gestión de claves (KMS) en Grid Manager
 a| 
Configure un servidor de administración de claves para el sitio StorageGRID (*CONFIGURACIÓN* > *Seguridad* > *servidor de administración de claves*) y active el cifrado de nodos para el dispositivo. A continuación, un nodo de dispositivo se conecta al KMS para solicitar una clave de cifrado (KEK). Esta clave cifra y descifra la clave de cifrado de datos (DEK) en cada volumen.
 a| 
Nodos de dispositivo con *cifrado de nodos* activado durante la instalación. Todos los datos del dispositivo están protegidos frente a la pérdida física o la eliminación del centro de datos. Se puede usar con algunos dispositivos de almacenamiento y servicios de StorageGRID.



 a| 
Drive Security en SANtricity System Manager
 a| 
Si la función Drive Security está habilitada para un dispositivo de almacenamiento, es posible usar SANtricity System Manager para crear y gestionar la clave de seguridad. Se requiere la clave para acceder a los datos en las unidades seguras.
 a| 
Dispositivos de almacenamiento con unidades de cifrado de disco completo (FDE) o unidades de estándar de procesamiento de información federal (FIPS). Todos los datos de las unidades seguras están protegidos frente a la pérdida física o eliminación del centro de datos. No se puede utilizar con algunos dispositivos de almacenamiento ni con ningún dispositivo de servicio.

* xref:../sg6000/index.adoc[Dispositivos de almacenamiento SG6000]
* xref:../sg5700/index.adoc[Dispositivos de almacenamiento SG5700]
* xref:../sg5600/index.adoc[Dispositivos de almacenamiento SG5600]




 a| 
Opción de cuadrícula de cifrado de objetos almacenados
 a| 
La opción *cifrado de objetos almacenados* se puede activar en Grid Manager (*CONFIGURACIÓN* > *sistema* > *Opciones de cuadrícula*). Cuando se habilita esta opción, todos los objetos nuevos que no se cifran a nivel de bloque o de objeto se cifran durante el procesamiento.
 a| 
Datos de objetos S3 y Swift recientemente procesados.

Los objetos almacenados existentes no están cifrados. Los metadatos de objetos y otros datos confidenciales no se cifran.

* xref:configuring-stored-object-encryption.adoc[Configurar el cifrado de objetos almacenados]




 a| 
Cifrado de bloques de S3
 a| 
Se emite una solicitud DE cifrado PUT Bucket para habilitar el cifrado en el bloque. Los objetos nuevos que no se cifren en el nivel de objeto se cifran durante el procesamiento.
 a| 
Solo datos de objetos S3 procesados recientemente.

Debe especificarse el cifrado para el bloque. Los objetos de bloque existentes no están cifrados. Los metadatos de objetos y otros datos confidenciales no se cifran.

* xref:../s3/index.adoc[Use S3]




 a| 
Cifrado del lado del servidor de objetos S3 (SSE)
 a| 
Se emite una solicitud de S3 para almacenar un objeto e incluir el `x-amz-server-side-encryption` solicite el encabezado.
 a| 
Solo datos de objetos S3 procesados recientemente.

Se debe especificar el cifrado para el objeto. Los metadatos de objetos y otros datos confidenciales no se cifran.

StorageGRID gestiona las claves.

* xref:../s3/index.adoc[Use S3]




 a| 
Cifrado del lado del servidor de objetos S3 con claves proporcionadas por el cliente (SSE-C)
 a| 
Se emite una solicitud S3 para almacenar un objeto e incluir tres encabezados de solicitud.

* `x-amz-server-side-encryption-customer-algorithm`
* `x-amz-server-side-encryption-customer-key`
* `x-amz-server-side-encryption-customer-key-MD5`

 a| 
Solo datos de objetos S3 procesados recientemente.

Se debe especificar el cifrado para el objeto. Los metadatos de objetos y otros datos confidenciales no se cifran.

Las claves se gestionan fuera de StorageGRID.

* xref:../s3/index.adoc[Use S3]




 a| 
Cifrado de volúmenes o almacenes de datos externos
 a| 
Si la plataforma de implementación lo admite, puede utilizar un método de cifrado fuera de StorageGRID para cifrar un volumen o almacén de datos completo.
 a| 
Todos los datos de objetos, metadatos y datos de configuración del sistema, suponiendo que se cifre cada volumen o almacén de datos.

Un método de cifrado externo proporciona un control más estricto sobre los algoritmos y claves de cifrado. Se puede combinar con los otros métodos enumerados.



 a| 
Cifrado de objetos fuera de StorageGRID
 a| 
Se utiliza un método de cifrado fuera de StorageGRID para cifrar los metadatos y los datos de objetos antes de que se ingieran en StorageGRID.
 a| 
Solo datos de objetos y metadatos (los datos de configuración del sistema no están cifrados).

Un método de cifrado externo proporciona un control más estricto sobre los algoritmos y claves de cifrado. Se puede combinar con los otros métodos enumerados.

* https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingClientSideEncryption.html["Amazon simple Storage Service - Guía para desarrolladores: Protección de datos mediante cifrado en el cliente"^]


|===


== Utilice varios métodos de cifrado

En función de los requisitos, puede utilizar más de un método de cifrado a la vez. Por ejemplo:

* Puede utilizar un KMS para proteger los nodos de dispositivos y también para usar la función de seguridad de unidades de System Manager de SANtricity a fin de «doble cifrado» de datos de las unidades de autocifrado de los mismos dispositivos.
* Puede usar un KMS para proteger los datos en los nodos del dispositivo y también puede usar la opción de cuadrícula de cifrado de objetos almacenados para cifrar todos los objetos cuando se ingieren.


Si solo una pequeña parte de los objetos requiere cifrado, considere la posibilidad de controlar el cifrado en el nivel de bloque o de objeto individual. Habilitar varios niveles de cifrado tiene un coste de rendimiento adicional.
