---
permalink: s3/changes-to-s3-rest-api-support.html 
sidebar: sidebar 
keywords: s3 rest api support changes 
summary: Debe conocer los cambios en la compatibilidad del sistema StorageGRID con la API DE REST de S3. 
---
= Cambios en la compatibilidad con la API DE REST de S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe estar al tanto de los cambios en la compatibilidad del sistema StorageGRID con la API DE REST de S3.

[cols="1a,4a"]
|===
| Liberar | Comentarios 


 a| 
11.6
 a| 
* Se ha agregado soporte para utilizar `partNumber` Parámetro de solicitud en GET Object y HEAD Object peticiones.
* Se añadió compatibilidad con un modo de retención predeterminado y un período de retención predeterminado en el nivel de bloque para S3 Object Lock.
* Se ha añadido compatibilidad con `s3:object-lock-remaining-retention-days` clave de condición de política para configurar el rango de períodos de retención permitidos para los objetos.
* El tamaño máximo _recommended_ para una única operación PUT Object es ahora de 5 GIB (5,368,709,120 bytes). Si tiene objetos que sean mayores de 5 GIB, utilice la carga de varias partes en su lugar.



IMPORTANT: En StorageGRID 11.6, el tamaño máximo _admitido_ para una única operación PUT Object sigue siendo de 5 TIB (5,497,558,138,880 bytes). Sin embargo, la alerta * S3 PUT Object size demasiado grande* se activará si intenta cargar un objeto que supere los 5 GIB.



 a| 
11.5
 a| 
* Se ha agregado compatibilidad para gestionar el cifrado de bloques.
* Se añadió compatibilidad con el bloqueo de objetos S3 y las solicitudes de cumplimiento heredadas obsoletas.
* Se ha agregado soporte para el uso DE DELETE Multiple Objects en cubos con versiones.
* La `Content-MD5` el encabezado de la solicitud ahora es correctamente compatible.




 a| 
11.4
 a| 
* Se añadió compatibilidad con el etiquetado DE bloques DE DELETE, GET Bucket y PUT Bucket. No se admiten etiquetas de asignación de costes.
* En el caso de bloques creados en StorageGRID 11.4, ya no es necesario restringir los nombres de claves de objetos para cumplir con las prácticas recomendadas de rendimiento.
* Se ha agregado compatibilidad con las notificaciones de bloques en la `s3:ObjectRestore:Post` tipo de evento.
* Ahora se aplican los límites de tamaño de AWS para piezas multiparte. Cada parte de una carga de varias partes debe tener entre 5 MIB y 5 GIB. La última parte puede ser menor que 5 MIB.
* Se ha agregado compatibilidad con TLS 1.3 y se ha actualizado la lista de conjuntos de cifrado TLS compatibles.
* El servicio CLB está obsoleto.




 a| 
11.3
 a| 
* Se ha añadido compatibilidad con el cifrado en el servidor de los datos de objetos con las claves proporcionadas por el cliente (SSE-C).
* Se ha añadido compatibilidad para operaciones DE ELIMINACIÓN, GET y PUT Bucket Lifecycle (solo acción de caducidad) y para el `x-amz-expiration` encabezado de respuesta.
* Se han actualizado PUT Object, PUT Object - Copy y Multipart Upload para describir el impacto de las reglas de ILM que utilizan la colocación síncrona en el procesamiento.
* Lista actualizada de conjuntos de cifrado TLS admitidos. Ya no se admiten los cifrados TLS 1.1.




 a| 
11.2
 a| 
Compatibilidad añadida para la restauración DE objetos POSTERIOR para uso con pools de almacenamiento en cloud. Se añadió compatibilidad con el uso de la sintaxis AWS para ARN, claves de condición de política y variables de política en políticas de grupos y bloques. Se seguirán soportando las políticas de grupo y bloque existentes que utilicen la sintaxis StorageGRID.

*Nota:* los usos de ARN/URN en otra configuración JSON/XML, incluidos los utilizados en las características personalizadas de StorageGRID, no han cambiado.



 a| 
11.1
 a| 
Se ha agregado soporte para uso compartido de recursos de origen cruzado (CORS), conexiones de clientes HTTP para S3 a nodos de grid y configuración de cumplimiento en bloques.



 a| 
11.0
 a| 
Se añadió compatibilidad para configurar servicios de plataforma (replicación de CloudMirror, notificaciones e integración de búsqueda de Elasticsearch) para los bloques. También se añadió compatibilidad con las restricciones de ubicación del etiquetado de objetos para bloques y la configuración de control de coherencia disponible.



 a| 
10.4
 a| 
Se ha agregado compatibilidad con los cambios de análisis de ILM en las versiones, las actualizaciones de página de nombres de dominio de extremo, las condiciones y variables en las directivas, los ejemplos de directivas y el permiso PutOverwriteObject.



 a| 
10.3
 a| 
Se ha añadido compatibilidad con las versiones.



 a| 
10.2
 a| 
Se ha añadido compatibilidad con las políticas de acceso a grupos y bloques y para la copia de varias partes (cargar artículo - copia).



 a| 
10.1
 a| 
Se añadió compatibilidad con la carga de varias partes, las solicitudes de estilo hospedado virtual y la autenticación v4.



 a| 
10.0
 a| 
Soporte inicial de la API DE REST de S3 por parte del sistema StorageGRID.la versión actualmente admitida de _simple Storage Service API Reference_ es 2006-03-01.

|===