---
permalink: s3/operations-on-objects.html 
sidebar: sidebar 
keywords: bucket, buckets, operations on buckets 
summary: En esta sección se describe cómo el sistema StorageGRID implementa operaciones de la API DE REST de S3 para objetos. 
---
= Operaciones en objetos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En esta sección se describe cómo el sistema StorageGRID implementa operaciones de la API DE REST de S3 para objetos.

Las siguientes condiciones se aplican a todas las operaciones de objeto:

* StorageGRID xref:consistency-controls.adoc[controles de consistencia] son compatibles con todas las operaciones de los objetos, con la excepción de lo siguiente:
+
** OBTENER ACL de objeto
** `OPTIONS /`
** PONER objeto legal
** PUT Object retention
** SELECCIONE Contenido de objeto


* Las solicitudes de clientes en conflicto, como dos clientes que escriben en la misma clave, se resuelven en función de las "últimas victorias". El plazo para la evaluación de "logros más recientes" se basa en cuándo el sistema StorageGRID completa una solicitud determinada, y no en cuándo los clientes S3 comienzan una operación.
* Todos los objetos de un bloque StorageGRID son propiedad del propietario del bloque, incluidos los objetos creados por un usuario anónimo o por otra cuenta.
* No se puede acceder a los objetos de datos procesados en el sistema StorageGRID a través de Swift a través de S3.


En la siguiente tabla se describe cómo StorageGRID implementa operaciones de objetos API DE REST de S3.

[cols="1a,2a"]
|===
| Funcionamiento | Implementación 


 a| 
ELIMINAR objeto
 a| 
Autenticación multifactor (MFA) y el encabezado de respuesta `x-amz-mfa` no son compatibles.

Al procesar una solicitud DE ELIMINACIÓN de objeto, StorageGRID intenta eliminar inmediatamente todas las copias del objeto de todas las ubicaciones almacenadas. Si se realiza correctamente, StorageGRID devuelve una respuesta al cliente inmediatamente. Si no se pueden eliminar todas las copias en un plazo de 30 segundos (por ejemplo, porque una ubicación no está disponible temporalmente), StorageGRID pone en cola las copias para su eliminación y luego indica que el cliente se ha realizado correctamente.

*Versioning*

Para eliminar una versión específica, el solicitante debe ser el propietario del bloque y utilizar el `versionId` subrecurso. El uso de este subrecurso elimina permanentemente la versión. Si la `versionId` corresponde a un marcador de borrado, el encabezado de respuesta `x-amz-delete-marker` se devuelve establecido en `true`.

* Si se elimina un objeto sin el `versionId` subrecurso en un bloque habilitado para la versión, da como resultado la generación de un marcador de borrado. La `versionId` para el marcador de borrado se devuelve mediante `x-amz-version-id` encabezado de respuesta, y el `x-amz-delete-marker` el encabezado de la respuesta se devuelve establecido en `true`.
* Si se elimina un objeto sin el `versionId` subrecurso en un bloque suspendido de la versión, se produce la eliminación permanente de una versión "nula" ya existente o un marcador de borrado "nula" y la generación de un nuevo marcador de borrado "nulo". La `x-amz-delete-marker` el encabezado de la respuesta se devuelve establecido en `true`.


*Nota*: En algunos casos, pueden existir varios marcadores de borrado para un objeto.



 a| 
ELIMINAR varios objetos
 a| 
Autenticación multifactor (MFA) y el encabezado de respuesta `x-amz-mfa` no son compatibles.

Se pueden eliminar varios objetos en el mismo mensaje de solicitud.



 a| 
ELIMINAR etiquetado de objetos
 a| 
Utiliza la `tagging` subrecurso para quitar todas las etiquetas de un objeto. Se implementa con todo el comportamiento de la API DE REST de Amazon S3.

*Versioning*

Si la `versionId` el parámetro de consulta no se especifica en la solicitud, la operación elimina todas las etiquetas de la versión más reciente del objeto en un bloque con versiones. Si la versión actual del objeto es un marcador de borrado, se devuelve el estado "MetodNotAllowed" con el `x-amz-delete-marker` encabezado de respuesta establecido en `true`.



 a| 
OBTENER objeto
 a| 
xref:get-object.adoc[OBTENER objeto]



 a| 
OBTENER ACL de objeto
 a| 
Si se proporcionan las credenciales de acceso necesarias para la cuenta, la operación devuelve una respuesta positiva y el ID, DisplayName y permiso del propietario del objeto, lo que indica que el propietario tiene acceso completo al objeto.



 a| 
OBTENER retención legal de objetos
 a| 
xref:using-s3-object-lock.adoc[Utilice el bloqueo de objetos de S3]



 a| 
OBTENGA retención de objetos
 a| 
xref:using-s3-object-lock.adoc[Utilice el bloqueo de objetos de S3]



 a| 
GET Object tagging
 a| 
Utiliza la `tagging` subrecurso para devolver todas las etiquetas de un objeto. Se implementa con todo el comportamiento de la API DE REST de Amazon S3

*Versioning*

Si la `versionId` el parámetro de consulta no se especifica en la solicitud, la operación devuelve todas las etiquetas de la versión más reciente del objeto en un bloque con versiones. Si la versión actual del objeto es un marcador de borrado, se devuelve el estado "MetodNotAllowed" con el `x-amz-delete-marker` encabezado de respuesta establecido en `true`.



 a| 
OBJETO HEAD
 a| 
xref:head-object.adoc[OBJETO HEAD]



 a| 
Restauración DE objetos posterior
 a| 
xref:post-object-restore.adoc[Restauración DE objetos posterior]



 a| 
OBJETO PUT
 a| 
xref:put-object.adoc[OBJETO PUT]



 a| 
PONER objeto: Copiar
 a| 
xref:put-object-copy.adoc[PONER objeto: Copiar]



 a| 
PONER objeto legal
 a| 
xref:using-s3-object-lock.adoc[Utilice el bloqueo de objetos de S3]



 a| 
PUT Object retention
 a| 
xref:using-s3-object-lock.adoc[Utilice el bloqueo de objetos de S3]



 a| 
PUT Object tagging
 a| 
Utiliza la `tagging` subrecurso para agregar un conjunto de etiquetas a un objeto existente. Se implementa con todo el comportamiento de la API DE REST de Amazon S3

*Límites de etiquetas de objeto*

Puede agregar etiquetas a nuevos objetos cuando los cargue o puede agregarlos a objetos existentes. Tanto StorageGRID como Amazon S3 admiten hasta 10 etiquetas por cada objeto. Las etiquetas asociadas a un objeto deben tener claves de etiqueta únicas. Una clave de etiqueta puede tener hasta 128 caracteres Unicode de longitud y los valores de etiqueta pueden tener hasta 256 caracteres Unicode de longitud. La clave y los valores distinguen entre mayúsculas y minúsculas.

*Actualizaciones de etiquetas y comportamiento de procesamiento*

Cuando se utiliza PUT Object tagging para actualizar las etiquetas de un objeto, StorageGRID no vuelve a procesar el objeto. Esto significa que no se utiliza la opción de comportamiento de ingesta especificada en la regla de ILM que coincide. Cualquier cambio en la ubicación del objeto que se active por la actualización se realice cuando los procesos de ILM normales se reevalúan el ILM en segundo plano.

Esto significa que si la regla ILM utiliza la opción estricta para el comportamiento de procesamiento, no se lleva a cabo ninguna acción si no se pueden realizar las ubicaciones de objetos necesarias (por ejemplo, porque una ubicación recientemente requerida no está disponible). El objeto actualizado conserva su ubicación actual hasta que sea posible la colocación requerida.

*Resolución de conflictos*

Las solicitudes de clientes en conflicto, como dos clientes que escriben en la misma clave, se resuelven en función de las "últimas victorias". El plazo para la evaluación de "logros más recientes" se basa en cuándo el sistema StorageGRID completa una solicitud determinada, y no en cuándo los clientes S3 comienzan una operación.

*Versioning*

Si la `versionId` el parámetro de consulta no se especifica en la solicitud, la operación agrega etiquetas a la versión más reciente del objeto en un bloque con versiones. Si la versión actual del objeto es un marcador de borrado, se devuelve el estado "MetodNotAllowed" con el `x-amz-delete-marker` encabezado de respuesta establecido en `true`.

|===
.Información relacionada
xref:s3-operations-tracked-in-audit-logs.adoc[Se realizó un seguimiento de las operaciones de S3 en los registros de auditoría]
