---
permalink: s3/recommendations-for-implementing-s3-rest-api.html 
sidebar: sidebar 
keywords: implement s3 rest api 
summary: Debe seguir estas recomendaciones al implementar la API DE REST de S3 para usar con StorageGRID. 
---
= Recomendaciones para implementar la API REST de S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe seguir estas recomendaciones al implementar la API DE REST de S3 para usar con StorageGRID.



== Recomendaciones para las cabezas a los objetos no existentes

Si su aplicación comprueba de forma rutinaria si existe un objeto en una ruta en la que no espera que el objeto exista realmente, debe utilizar el control de consistencia "'disponible'". Por ejemplo, debe utilizar el control de coherencia "'disponible'" si su aplicación dirige una ubicación antes DE PONERLA en práctica.

De lo contrario, si la operación HEAD no encuentra el objeto, es posible que reciba un número elevado de 500 errores internos de Server si uno o más nodos de almacenamiento no están disponibles.

Puede establecer el control de consistencia "'Available'" para cada bloque mediante LA solicitud DE consistencia PUT Bucket, o bien puede especificar el control de consistencia en el encabezado de solicitud para una operación de API individual.



== Recomendaciones para las claves de objeto

En el caso de los bloques creados en StorageGRID 11.4 o posterior, ya no es necesario restringir los nombres de claves de objetos para cumplir con las prácticas recomendadas de rendimiento. Por ejemplo, ahora puede utilizar valores aleatorios para los primeros cuatro caracteres de nombres de claves de objeto.

Para los bloques que se crearon en las versiones anteriores a StorageGRID 11.4, siga estas recomendaciones para los nombres de claves de objetos:

* No debe utilizar valores aleatorios como los primeros cuatro caracteres de claves de objeto. Esto contrasta con la anterior recomendación de AWS para prefijos clave. En su lugar, debe utilizar prefijos no aleatorios y no únicos, como `image`.
* Si sigue la recomendación anterior de AWS de utilizar caracteres aleatorios y únicos en prefijos clave, debe anteponer las claves de objeto con un nombre de directorio. Es decir, utilice este formato:
+
[listing]
----
mybucket/mydir/f8e3-image3132.jpg
----
+
En lugar de este formato:

+
[listing]
----
mybucket/f8e3-image3132.jpg
----




== Recomendaciones para «lecturas de rango»

Si se selecciona la opción *Compress Stored Objects* (*CONFIGURATION* > *System* > *Grid options*), las aplicaciones cliente S3 deberían evitar realizar operaciones GET Object que especifiquen un intervalo de bytes. Estas operaciones de «lectura de rango» son ineficientes, ya que StorageGRID debe descomprimir de forma efectiva los objetos para acceder a los bytes solicitados. LAS operaciones GET Object que solicitan un rango pequeño de bytes de un objeto muy grande son especialmente ineficientes; por ejemplo, es muy ineficiente leer un rango de 10 MB de un objeto comprimido de 50 GB.

Si se leen rangos de objetos comprimidos, las solicitudes del cliente pueden tener un tiempo de espera.


NOTE: Si necesita comprimir objetos y su aplicación cliente debe utilizar lecturas de rango, aumente el tiempo de espera de lectura de la aplicación.

.Información relacionada
* xref:consistency-controls.adoc[Controles de consistencia]
* xref:put-bucket-consistency-request.adoc[PONER solicitud de consistencia de bloque]
* xref:../admin/index.adoc[Administre StorageGRID]

