---
permalink: monitor/deployment-and-maintenance-logs.html 
sidebar: sidebar 
keywords: deployment, logs, Maintenance 
summary: Puede utilizar los registros de implementación y de mantenimiento para solucionar problemas. 
---
= Registros de implementación y mantenimiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar los registros de implementación y de mantenimiento para solucionar problemas.

|===
| Nombre de archivo | Notas | Encontrado en 


 a| 
`/var/local/log/install.log`
 a| 
Creado durante la instalación del software. Contiene un registro de los eventos de instalación.
 a| 
Todos los nodos



 a| 
`/var/local/log/expansion-progress.log`
 a| 
Creado durante las operaciones de expansión. Contiene un registro de los eventos de expansión.
 a| 
Nodos de almacenamiento



 a| 
`/var/local/log/gdu-server.log`
 a| 
Creado por el servicio GDU. Contiene eventos relacionados con los procedimientos de aprovisionamiento y mantenimiento gestionados por el nodo de administración principal.
 a| 
Nodo de administrador principal



 a| 
`/var/local/log/send_admin_hw.log`
 a| 
Creado durante la instalación. Contiene información de depuración relacionada con las comunicaciones de un nodo con el nodo de administración principal.
 a| 
Todos los nodos



 a| 
`/var/local/log/upgrade.log`
 a| 
Creado durante la actualización de software. Contiene un registro de los eventos de actualización de software.
 a| 
Todos los nodos

|===