---
permalink: monitor/monitoring-load-balancing-operations.html 
sidebar: sidebar 
keywords: load balancing, monitoring 
summary: Si está utilizando un equilibrador de carga para gestionar las conexiones de cliente a StorageGRID, debe supervisar las operaciones de equilibrio de carga después de configurar el sistema inicialmente y después de realizar cualquier cambio de configuración o llevar a cabo una ampliación. 
---
= Supervisar las operaciones de equilibrio de carga
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si está utilizando un equilibrador de carga para gestionar las conexiones de cliente a StorageGRID, debe supervisar las operaciones de equilibrio de carga después de configurar el sistema inicialmente y después de realizar cualquier cambio de configuración o llevar a cabo una ampliación.

.Lo que necesitará
* Debe iniciar sesión en Grid Manager mediante un xref:../admin/web-browser-requirements.adoc[navegador web compatible].
* Debe tener permisos de acceso específicos.


.Acerca de esta tarea
Puede utilizar el servicio Load Balancer en nodos de administración o de puerta de enlace, un equilibrador de carga de terceros externo o el servicio CLB en nodos de Gateway para distribuir solicitudes de cliente en varios nodos de almacenamiento.


NOTE: El servicio CLB está obsoleto.

Después de configurar el equilibrio de carga, debe confirmar que las operaciones de ingesta y recuperación de objetos se encuentren distribuidas uniformemente en los nodos de almacenamiento. Las solicitudes distribuidas de forma equitativa garantizan que StorageGRID sigue respondiendo a las solicitudes de los clientes bajo carga y pueden ayudar a mantener el rendimiento del cliente.

Si configuró un grupo de alta disponibilidad de nodos de puerta de enlace o nodos de administración en modo de backup activo, solo un nodo del grupo distribuye de forma activa las solicitudes de cliente.

Consulte la sección sobre la configuración de conexiones de cliente en las instrucciones para administrar StorageGRID.

.Pasos
. Si los clientes S3 o Swift se conectan mediante el servicio Load Balancer, compruebe que los nodos de administración o de puerta de enlace distribuyan de forma activa el tráfico según lo previsto:
+
.. Seleccione *NODES*.
.. Seleccione un nodo de puerta de enlace o un nodo de administrador.
.. En la ficha *Descripción general*, compruebe si una interfaz de nodo está en un grupo ha y si la interfaz de nodo tiene la función Master.
+
Los nodos con la función de nodo maestro y los nodos que no están en un grupo de alta disponibilidad deben distribuir activamente las solicitudes a los clientes.

.. Para cada nodo que deba distribuir activamente solicitudes de cliente, seleccione la pestaña *Load Balancer*.
.. Revise el gráfico de Load Balancer Request Traffic de la última semana para asegurarse de que el nodo ha estado distribuyendo solicitudes de forma activa.
+
Los nodos de un grupo de alta disponibilidad de backup activo pueden asumir el rol de backup de vez en cuando. Durante ese tiempo, los nodos no distribuyen las solicitudes del cliente.

.. Revise el gráfico de la velocidad de solicitud entrante del equilibrador de carga de la última semana para revisar el rendimiento del objeto del nodo.
.. Repita estos pasos para cada nodo de administración o nodo de puerta de enlace del sistema StorageGRID.
.. De manera opcional, utilice las políticas de clasificación de tráfico para ver un desglose más detallado del tráfico que presta el servicio Load Balancer.


. Si los clientes S3 o Swift se conectan mediante el servicio CLB (obsoleto), realice las siguientes comprobaciones:
+
.. Seleccione *NODES*.
.. Seleccione un nodo de puerta de enlace.
.. En la ficha *Descripción general*, compruebe si una interfaz de nodo está en un grupo ha y si la interfaz de nodo tiene la función de Master.
+
Los nodos con la función de nodo maestro y los nodos que no están en un grupo de alta disponibilidad deben distribuir activamente las solicitudes a los clientes.

.. Para cada nodo de puerta de enlace que debería distribuir activamente solicitudes de cliente, seleccione *SUPPORT* > *Tools* > *Topología de cuadrícula*.
.. Seleccione *_Gateway Node_* > *CLB* > *HTTP* > *Descripción general* > *Principal*.
.. Revise el número de *sesiones entrantes - establecidas* para comprobar que el nodo de puerta de enlace ha estado gestionando las solicitudes de forma activa.


. Compruebe que estas solicitudes se distribuyen uniformemente en los nodos de almacenamiento.
+
.. Seleccione *_Storage Node_* > *LDR* > *HTTP*.
.. Revisar el número de *sesiones entrantes actualmente establecidas*.
.. Repita esto para cada nodo de almacenamiento de la cuadrícula.
+
El número de sesiones debe ser aproximadamente igual en todos los nodos de almacenamiento.





.Información relacionada
xref:../admin/index.adoc[Administre StorageGRID]

xref:viewing-load-balancer-tab.adoc[Vea la pestaña Load Balancer]
