---
permalink: monitor/using-snmp-monitoring.html 
sidebar: sidebar 
keywords: snmp, monitoring 
summary: 'Si desea supervisar StorageGRID mediante el protocolo simple de administración de red \(SNMP\), debe configurar el agente SNMP que se incluye con StorageGRID.' 
---
= Usar supervisión de SNMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si desea supervisar StorageGRID mediante el protocolo simple de gestión de redes (SNMP), debe configurar el agente SNMP que se incluye con StorageGRID.

* xref:configuring-snmp-agent.adoc[Configure el agente SNMP]
* xref:updating-snmp-agent.adoc[Actualice el agente SNMP]




== Funcionalidades

Cada nodo StorageGRID ejecuta un agente SNMP, o un daemon, que proporciona una base de datos de información de gestión (MIB). El MIB de StorageGRID contiene definiciones de tablas y notificaciones para alertas y alarmas. El MIB también contiene información de descripción del sistema, como la plataforma y el número de modelo de cada nodo. Cada nodo StorageGRID también admite un subconjunto de objetos MIB-II.

Inicialmente, SNMP está deshabilitado en todos los nodos. Al configurar el agente SNMP, todos los nodos StorageGRID reciben la misma configuración.

El agente SNMP de StorageGRID admite las tres versiones del protocolo SNMP. Proporciona acceso MIB de solo lectura para consultas, y puede enviar dos tipos de notificaciones condicionadas por eventos a un sistema de gestión:

* *Trampas* son notificaciones enviadas por el agente SNMP que no requieren el reconocimiento del sistema de administración. Los traps sirven para notificar al sistema de gestión que algo ha sucedido dentro de StorageGRID, por ejemplo, que se activa una alerta.
+
Las tres versiones de SNMP admiten capturas.

* *Informa* es similar a las trampas, pero requieren el reconocimiento del sistema de administración. Si el agente SNMP no recibe un acuse de recibo en un periodo de tiempo determinado, vuelve a enviar el informe hasta que se reciba un acuse de recibo o se haya alcanzado el valor de reintento máximo.
+
Las informa son compatibles con SNMPv2c y SNMPv3.



Las notificaciones Trap e INFORM se envían en los siguientes casos:

* Una alerta predeterminada o personalizada se activa en cualquier nivel de gravedad. Para suprimir las notificaciones SNMP de una alerta, debe configurar un silencio para la alerta. Las notificaciones de alerta se envían mediante el nodo de administrador que esté configurado para que sea el remitente preferido.
+
Cada alerta se asigna a uno de los tres tipos de trampa según el nivel de gravedad de la alerta: ActiveMinorAlert, activeMajorAlert y activeCriticalAlert. Para obtener descripciones de las alertas que pueden desencadenar estos retos, consulte xref:alerts-reference.adoc[Referencia de alertas].

* Ciertas alarmas (sistema heredado) se activan a niveles de gravedad especificados o superiores.
+

NOTE: Las notificaciones SNMP no se envían para cada alarma ni para cada gravedad de alarma.





== Compatibilidad con versiones de SNMP

La tabla proporciona un resumen a grandes rasgos de lo que se admite para cada versión de SNMP.

|===
|  | SNMPv1 | SNMPv2c | SNMPv3 


 a| 
Consultas
 a| 
Consultas MIB de solo lectura
 a| 
Consultas MIB de solo lectura
 a| 
Consultas MIB de solo lectura



 a| 
Consulta de autenticación
 a| 
Cadena de comunidad
 a| 
Cadena de comunidad
 a| 
Usuario del modelo de seguridad basado en el usuario (USM)



 a| 
Notificaciones
 a| 
Sólo capturas
 a| 
Atrapa e informa
 a| 
Atrapa e informa



 a| 
Autenticación de notificaciones
 a| 
Comunidad de capturas predeterminada o una cadena de comunidad personalizada para cada destino de capturas
 a| 
Comunidad de capturas predeterminada o una cadena de comunidad personalizada para cada destino de capturas
 a| 
Usuario USM en cada destino de captura

|===


== Limitaciones

* StorageGRID admite acceso MIB de solo lectura. No se admite el acceso de lectura y escritura.
* Todos los nodos de la cuadrícula reciben la misma configuración.
* SNMPv3: StorageGRID no admite el modo de soporte para transporte (TSM).
* SNMPv3: El único protocolo de autenticación compatible es SHA (HMAC-SHA-96).
* SNMPv3: El único protocolo de privacidad compatible es AES.




== Acceda a la MIB

Puede acceder al archivo de definición MIB en la siguiente ubicación en cualquier nodo StorageGRID:

`/usr/share/snmp/mibs/NETAPP-STORAGEGRID-MIB.txt`

.Información relacionada
* xref:alerts-reference.adoc[Referencia de alertas]
* xref:alarms-reference.adoc[Referencia de alarmas (sistema heredado)]
* xref:alarms-that-generate-snmp-notifications.adoc[Alarmas que generan notificaciones SNMP (sistema heredado)]
* xref:silencing-alert-notifications.adoc[Silenciar notificaciones de alerta]

