---
permalink: maintain/configuring-dns-servers.html 
sidebar: sidebar 
keywords: storagegrid, dns, configuring dns, configure dns, domain name system 
summary: 'Puede agregar, quitar y actualizar servidores de sistema de nombres de dominio \(DNS\) para que pueda utilizar nombres de host completos \(FQDN\) en lugar de direcciones IP.' 
---
= Configure los servidores DNS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede agregar, quitar y actualizar servidores de sistema de nombres de dominio (DNS) para poder usar nombres de host de nombre de dominio completo (FQDN) en lugar de direcciones IP.

.Lo que necesitará
* Debe iniciar sesión en Grid Manager mediante un xref:../admin/web-browser-requirements.adoc[navegador web compatible].
* Debe tener los permisos de mantenimiento o acceso raíz.
* Debe tener las direcciones IP de los servidores DNS para configurar.


Al especificar información del servidor DNS, se pueden utilizar nombres de host de nombre de dominio completo (FQDN) en lugar de direcciones IP para notificaciones por correo electrónico o SNMP y AutoSupport. Se recomienda especificar al menos dos servidores DNS.


IMPORTANT: Proporcione entre dos y seis direcciones IP para los servidores DNS. En general, seleccione los servidores DNS a los que cada sitio puede acceder localmente en el caso de que la red sea Landing. Esto es para asegurar que un sitio de Ilanded siga teniendo acceso al servicio DNS. Después de configurar la lista de servidores DNS de toda la cuadrícula, puede xref:modifying-dns-configuration-for-single-grid-node.adoc[Personalice aún más la lista de servidores DNS para cada nodo].

Si se omite o se configura incorrectamente la información del servidor DNS, se activa una alarma DNST en el servicio SSM de cada nodo de cuadrícula. La alarma se borra cuando DNS está configurado correctamente y la nueva información del servidor ha llegado a todos los nodos de la cuadrícula.

.Pasos
. Seleccione *MANTENIMIENTO* *Red* *servidores DNS*.
. En la sección servidores, agregue actualizaciones o elimine las entradas del servidor DNS, según sea necesario.
+
La práctica recomendada es especificar al menos dos servidores DNS por sitio. Puede especificar hasta seis servidores DNS.

. Haga clic en *Guardar*.

