---
permalink: maintain/downloading-recovery-package.html 
sidebar: sidebar 
keywords: storagegrid, recovery package 
summary: El archivo de paquete de recuperación permite restaurar el sistema StorageGRID en caso de producirse un fallo. 
---
= Descargue el paquete de recuperación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El archivo de paquete de recuperación permite restaurar el sistema StorageGRID en caso de producirse un fallo.

.Lo que necesitará
* Debe iniciar sesión en Grid Manager mediante un xref:../admin/web-browser-requirements.adoc[navegador web compatible].
* Debe tener la clave de acceso de aprovisionamiento.
* Debe tener permisos de acceso específicos.


Descargue el archivo de paquete de recuperación actual antes de realizar cambios en la topología de la cuadrícula en el sistema StorageGRID o antes de actualizar el software. A continuación, descargue una nueva copia del paquete de recuperación después de realizar cambios en la topología de la cuadrícula o después de actualizar el software.

.Pasos
. Seleccione *MANTENIMIENTO* > *sistema* > *paquete de recuperación*.
. Introduzca la frase de acceso de aprovisionamiento y seleccione *Iniciar descarga*.
+
La descarga comienza inmediatamente.

. Cuando finalice la descarga:
+
.. Abra el `.zip` archivo.
.. Confirme que incluye un directorio gpt-backup y un directorio interno `.zip` archivo.
.. Extraer el interior `.zip` archivo.
.. Confirme que puede abrir el `Passwords.txt` archivo.


. Copie el archivo del paquete de recuperación descargado (`.zip`) a dos ubicaciones seguras, seguras y separadas.
+

IMPORTANT: El archivo del paquete de recuperación debe estar protegido porque contiene claves de cifrado y contraseñas que se pueden usar para obtener datos del sistema StorageGRID.



.Información relacionada
xref:../admin/index.adoc[Administre StorageGRID]
