---
permalink: maintain/rebooting-grid-node.html 
sidebar: sidebar 
keywords: reboot grid node 
summary: Puede reiniciar un nodo de cuadrícula desde Grid Manager o desde el shell de comandos del nodo. 
---
= Reinicie el nodo de cuadrícula
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede reiniciar un nodo de cuadrícula desde Grid Manager o desde el shell de comandos del nodo.

.Acerca de esta tarea
Cuando reinicia un nodo de cuadrícula, el nodo se apaga y se reinicia. Todos los servicios se reinician automáticamente.

Si planea reiniciar nodos de almacenamiento, tenga en cuenta lo siguiente:

* Si una regla de ILM especifica un comportamiento de procesamiento del COMMIT doble o la regla especifica un equilibrio y no es posible crear de inmediato todas las copias necesarias, StorageGRID confirma de inmediato cualquier objeto recién ingerido en dos nodos de almacenamiento en el mismo sitio y evalúa ILM más adelante. Si desea reiniciar dos o más nodos de almacenamiento en un sitio determinado, es posible que no pueda acceder a estos objetos durante el reinicio.
* Para garantizar que puede acceder a todos los objetos mientras se reinicia un nodo de almacenamiento, deje de procesar objetos en un sitio durante aproximadamente una hora antes de reiniciar el nodo.


.Información relacionada
xref:../admin/index.adoc[Administre StorageGRID]
