---
permalink: maintain/removing-donotstart-file-for-service.html 
sidebar: sidebar 
keywords: storagegrid, recover, donotstart file, do not start file, remove donotstart, removing donotstart, remove do not start, removing do not start 
summary: Al quitar un archivo DoNotStart que impide que se inicie un servicio, debe iniciar dicho servicio. 
---
= Quitar el archivo DoNotStart para el servicio técnico
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al quitar un archivo DoNotStart que impide que se inicie un servicio, debe iniciar dicho servicio.

.Lo que necesitará
Debe tener la `Passwords.txt` archivo.

.Pasos
. Inicie sesión en el nodo de grid:
+
.. Introduzca el siguiente comando: `ssh admin@_grid_node_IP_`
.. Introduzca la contraseña que aparece en `Passwords.txt` archivo.
.. Introduzca el siguiente comando para cambiar a la raíz: `su -`
.. Introduzca la contraseña que aparece en `Passwords.txt` archivo.


+
Cuando ha iniciado sesión como root, el símbolo del sistema cambia de `$` para `#`.

. Elimine el archivo DoNotStart del directorio de servicios: `rm /etc/sv/_service_/DoNotStart`
+
donde `service` es el nombre del servicio. Por ejemplo:

+
[listing]
----
rm /etc/sv/ldr/DoNotStart
----
. Inicie el servicio: `service _servicename_ start`
. Cierre la sesión del shell de comandos: `exit`

