---
permalink: maintain/removing-port-remaps.html 
sidebar: sidebar 
keywords: storagegrid, recover, remove port remap, removing port remap, port remap 
summary: Si desea configurar un extremo para el servicio Load Balancer y desea utilizar un puerto que ya se ha configurado como el puerto asignado a un remap de puertos, primero debe eliminar el remap de puertos existente o el extremo no será efectivo. Debe ejecutar una secuencia de comandos en cada nodo de administración y nodo de puerta de enlace que tenga puertos reasignados en conflicto para eliminar todas las reasignaciones de puertos del nodo. 
---
= Eliminar reasignaciones de puertos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si desea configurar un extremo para el servicio Load Balancer y desea utilizar un puerto que ya se ha configurado como el puerto asignado a un remap de puertos, primero debe eliminar el remap de puertos existente o el extremo no será efectivo. Debe ejecutar un script en cada nodo de administración y nodo de puerta de enlace que tenga puertos reasignados en conflicto para quitar todas las reasignaciones de puertos del nodo.

.Acerca de esta tarea

CAUTION: Este procedimiento quita todas las reasignaciones de puertos. Si necesita conservar parte de los remapas, póngase en contacto con el soporte técnico.

Para obtener información sobre la configuración de puntos finales del equilibrador de carga, consulte las instrucciones para administrar StorageGRID.


IMPORTANT: Si el remasterp de puertos proporciona acceso al cliente, debe volver a configurarse el cliente para utilizar un puerto diferente configurado como extremo de equilibrio de carga si es posible, para evitar la pérdida del servicio. De lo contrario, si se elimina la asignación de puertos se producirá una pérdida de acceso al cliente y se debe programar adecuadamente.


IMPORTANT: Este procedimiento no funciona en un sistema StorageGRID implementado como contenedor en hosts con configuración básica. Consulte las instrucciones para xref:removing-port-remaps-on-bare-metal-hosts.adoc[quitar mapas de puertos en hosts sin sistema operativo].

.Pasos
. Inicie sesión en el nodo.
+
.. Introduzca el siguiente comando: `ssh -p 8022 admin@node_IP`
+
El puerto 8022 es el puerto SSH del sistema operativo base, mientras que el puerto 22 es el puerto SSH del motor del contenedor que ejecuta StorageGRID.

.. Introduzca la contraseña que aparece en `Passwords.txt` archivo.
.. Introduzca el siguiente comando para cambiar a la raíz: `su -`
.. Introduzca la contraseña que aparece en `Passwords.txt` archivo.
+
Cuando ha iniciado sesión como root, el símbolo del sistema cambia de `$` para `#`.



. Ejecute el siguiente script: `remove-port-remap.sh`
. Reiniciar el nodo.
+
Siga las instrucciones para xref:rebooting-grid-node.adoc[reiniciar un nodo de cuadrícula].

. Repita estos pasos en cada nodo de administrador y nodo de puerta de enlace que tenga puertos reasignados en conflicto.


.Información relacionada
xref:../admin/index.adoc[Administre StorageGRID]
