---
permalink: maintain/using-donotstart-file.html 
sidebar: sidebar 
keywords: storagegrid, recover, donotstart, do not start, donotstart file, do not start file 
summary: Si está realizando varios procedimientos de mantenimiento o configuración bajo la dirección del soporte técnico, es posible que se le solicite que utilice un archivo DoNotStart para evitar que los servicios se inicien cuando se inicie o reinicie Server Manager. 
---
= Utilice un archivo DoNotStart
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si está realizando varios procedimientos de mantenimiento o configuración bajo la dirección del soporte técnico, es posible que se le solicite que utilice un archivo DoNotStart para evitar que los servicios se inicien cuando se inicie o reinicie Server Manager.


IMPORTANT: Debe agregar o quitar un archivo DoNotStart sólo si el soporte técnico le ha indicado que lo haga.

Para evitar que se inicie un servicio, coloque un archivo DoNotStart en el directorio del servicio que desea impedir que se inicie. Al iniciar, el Administrador del servidor busca el archivo DoNotStart. Si el archivo está presente, se impide que se inicie el servicio (y cualquier servicio que dependa de él). Cuando se quita el archivo DoNotStart, el servicio detenido anteriormente se iniciará en el siguiente inicio o reinicio de Server Manager. Los servicios no se inician automáticamente al quitar el archivo DoNotStart.

La forma más eficaz de evitar que todos los servicios se reinicien es impedir que se inicie el servicio NTP. Todos los servicios dependen del servicio NTP y no se pueden ejecutar si el servicio NTP no está en ejecución.
