---
permalink: primer/managing-tenants-and-client-connections.html 
sidebar: sidebar 
keywords: tenant, client, connect, connection 
summary: Como administrador de grid, puede crear y gestionar las cuentas de inquilino que utilizan los clientes S3 y Swift para almacenar y recuperar objetos, así como gestionar las opciones de configuración que controlan la forma en la que se conectan los clientes con su sistema StorageGRID. 
---
= Gestione inquilinos y conexiones de clientes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Como administrador de grid, puede crear y gestionar las cuentas de inquilino que utilizan los clientes S3 y Swift para almacenar y recuperar objetos, así como gestionar las opciones de configuración que controlan la forma en la que se conectan los clientes con su sistema StorageGRID.



== Cuentas de inquilino

Una cuenta de inquilino permite especificar quién puede usar su sistema de StorageGRID para almacenar y recuperar objetos, y qué funcionalidad está disponible para ellos. Las cuentas de inquilino permiten a las aplicaciones cliente que admiten la API DE REST de S3 o la API DE REST de Swift almacenar y recuperar objetos en StorageGRID. Cada cuenta de inquilino usa el protocolo de cliente S3 o el protocolo de cliente Swift.

Debe crear al menos una cuenta de inquilino para cada protocolo de cliente que se utilizará para almacenar los objetos en su sistema StorageGRID. Opcionalmente, puede crear cuentas de arrendatario adicionales si desea segregar los objetos almacenados en su sistema por entidades diferentes. Cada cuenta de inquilino tiene sus propios grupos y usuarios locales o federados, y sus propios bloques (contenedores para Swift) y objetos.

Puede utilizar Grid Manager o la API de gestión de grid para crear cuentas de inquilino. Al crear una cuenta de inquilino, especifique la siguiente información:

* Nombre para mostrar del arrendatario (el ID de cuenta del arrendatario se asigna automáticamente y no se puede modificar).
* Si la cuenta de inquilino usa S3 o Swift.
* Para las cuentas de inquilino de S3: Si la cuenta de inquilino está permitida para usar los servicios de la plataforma. Si se permite el uso de servicios de plataforma, la cuadrícula debe configurarse para que admita su uso.
* Opcionalmente, una cuota de almacenamiento para la cuenta de inquilino: El número máximo de gigabytes, terabytes o petabytes disponibles para los objetos del inquilino. La cuota de almacenamiento de un inquilino representa una cantidad lógica (tamaño de objeto), no una cantidad física (tamaño en disco).
* Si está habilitada la federación de identidades para el sistema StorageGRID, el grupo federado tiene permiso de acceso raíz para configurar la cuenta de inquilino.
* Si el sistema StorageGRID no utiliza el inicio de sesión único (SSO), tanto si la cuenta de inquilino usará su propio origen de identidad como si comparte el origen de identidad de la cuadrícula, así como la contraseña inicial del usuario raíz local del inquilino.


Si las cuentas de inquilinos S3 deben cumplir con los requisitos normativos, los administradores del grid pueden habilitar el valor global de bloqueo de objetos S3 para el sistema StorageGRID. Cuando se habilita S3 Object Lock para el sistema, todas las cuentas de inquilinos S3 pueden crear bloques con S3 Object Lock habilitado y, a continuación, especificar la configuración de retención y conservación legal para las versiones de objetos en ese bloque.

Después de crear una cuenta de inquilino, los usuarios de inquilino pueden iniciar sesión en el Administrador de inquilinos.



== Conexiones cliente a los nodos StorageGRID

Para que los usuarios inquilinos puedan usar clientes S3 o Swift para almacenar y recuperar datos en StorageGRID, debe decidir cómo se conectan estos clientes a los nodos de StorageGRID.

Las aplicaciones cliente pueden almacenar o recuperar objetos conectándose a cualquiera de los siguientes elementos:

* El servicio Load Balancer en nodos de administrador o nodos de puerta de enlace. Esta es la conexión recomendada.
* El servicio CLB en los nodos de puerta de enlace.
+

NOTE: El servicio CLB está obsoleto.

* Nodos de almacenamiento, con o sin un equilibrador de carga externo.


Al configurar StorageGRID para que los clientes puedan utilizar el servicio Load Balancer, debe realizar los siguientes pasos:

. Opcionalmente, configure los grupos de alta disponibilidad. Si crea un grupo de alta disponibilidad, las interfaces de varios nodos de administrador y nodos de puerta de enlace se colocan en una configuración de backup activo. Las conexiones de clientes se realizan mediante la dirección IP virtual del grupo de alta disponibilidad.
. Configure los extremos para el servicio Load Balancer. El servicio Load Balancer en los nodos de administrador o de puerta de enlace distribuye conexiones de red entrantes desde aplicaciones cliente hasta los nodos de almacenamiento. Al crear un extremo de equilibrio de carga, especifica un número de puerto, si el extremo acepta conexiones HTTP o HTTPS, el tipo de cliente (S3 o Swift) que utilizará el extremo y el certificado que se utilizará para las conexiones HTTPS (si procede).
. Opcionalmente, especifique que la red de cliente de un nodo no es de confianza para asegurarse de que todas las conexiones a la red de cliente del nodo se producen en los extremos del equilibrador de carga.


.Información relacionada
* xref:../admin/index.adoc[Administre StorageGRID]
* xref:../tenant/index.adoc[Usar una cuenta de inquilino]
* xref:../s3/index.adoc[Use S3]
* xref:../swift/index.adoc[Use Swift]
* xref:exploring-tenant-manager.adoc[Explore el responsable de inquilinos]
* xref:configuring-network-settings.adoc[Configure los ajustes de red]

