---
permalink: sg5700/hardware-setup-appears-to-hang.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, troubleshoot, troubleshooting, hardware, setup, hang, hangs, fails, failure, stop, terminate, terminates, stuck 
summary: Es posible que el instalador de dispositivos StorageGRID no esté disponible si los errores de hardware o de cableado impiden que la controladora E5700SG complete su procesamiento de arranque. 
---
= La configuración del hardware parece que se bloquea (SG5700)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que el instalador de dispositivos StorageGRID no esté disponible si los errores de hardware o de cableado impiden que la controladora E5700SG complete su procesamiento de arranque.

.Pasos
. Observe los códigos en las pantallas de siete segmentos.
+
Mientras el hardware se está inicializando durante el encendido, las dos pantallas de siete segmentos muestran una secuencia de códigos. Cuando el hardware se arranca correctamente, las pantallas de siete segmentos muestran códigos diferentes para cada controladora.

. Revise los códigos de la pantalla de siete segmentos del controlador E5700SG.
+

NOTE: La instalación y el aprovisionamiento tardan en realizarse. Algunas fases de instalación no notifican las actualizaciones del instalador de dispositivos StorageGRID durante varios minutos.

+
Si se produce un error, la pantalla de siete segmentos parpadea en una secuencia, como ÉL.

. Para comprender qué significan estos códigos, consulte los siguientes recursos:
+
|===
| Controladora | Referencia 


 a| 
Controladora E5700SG
 a| 
** "Indicadores de Estados en el controlador E5700SG"
** "'he error: Sincronización de errores con el software de sistema operativo SANtricity'"




 a| 
Controladora E2800
 a| 
_E5700 y Guía de supervisión del sistema E2800_

*Nota:* los códigos descritos para el controlador E5700 E-Series no se aplican al controlador E5700SG del aparato.

|===
. Si esto no se resuelve el problema, póngase en contacto con el soporte técnico.


.Información relacionada
xref:status-indicators-on-e5700sg-controller.adoc[Indicadores de estado en el controlador E5700SG]

xref:he-error-error-synchronizing-with-santricity-os-software.adoc[Error: Error al sincronizar con el software de sistema operativo SANtricity]

http://["Sitio de documentación para sistemas E-Series y EF-Series de NetApp"^]
