---
permalink: sg5700/optional-changing-raid-mode-sg5760-only.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, raid, raid mode, change, changing, modify, DDP, ddp16, raid6 
summary: Si tiene un SG5760 con 60 unidades, puede cambiar a otro modo RAID para adaptarse a sus requisitos de almacenamiento y recuperación. Solo puede cambiar el modo antes de implementar el nodo de almacenamiento del dispositivo StorageGRID. 
---
= Opcional: Cambiar el modo RAID (solo SG5760)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si tiene un SG5760 con 60 unidades, puede cambiar a otro modo RAID para adaptarse a sus requisitos de almacenamiento y recuperación. Solo puede cambiar el modo antes de implementar el nodo de almacenamiento del dispositivo StorageGRID.

.Lo que necesitará
* Tiene un SG5760. Si tiene un SG5712, debe usar el modo DDP.
* Está utilizando cualquier cliente que pueda conectarse a StorageGRID.
* El cliente tiene un xref:../admin/web-browser-requirements.adoc[navegador web compatible].


.Acerca de esta tarea
Antes de implementar el dispositivo SG5760 como nodo de almacenamiento, puede seleccionar una de las siguientes opciones de configuración de volúmenes:

* *DDP*: Este modo utiliza dos unidades de paridad por cada ocho unidades de datos. Éste es el modo predeterminado y recomendado para todos los dispositivos. En comparación con RAID6, los DDP ofrecen mejor rendimiento del sistema, reducen los tiempos de recompilación después de fallos de unidad y facilitan la gestión. Además, DDP ofrece protección contra pérdida de cajón en dispositivos de 60 unidades.
* *DDP16*: Este modo utiliza dos unidades de paridad por cada 16 unidades de datos, lo que da como resultado una mayor eficiencia de almacenamiento en comparación con DDP. En comparación con RAID6, DDP16 ofrece un mejor rendimiento del sistema, menores tiempos de recompilación después de fallos de unidad, facilidad de gestión y una eficiencia de almacenamiento similar. Para utilizar el modo DDP16, la configuración debe contener al menos 20 unidades. DDP16 no ofrece protección contra pérdida de cajón.
* *RAID6*: Este modo utiliza dos unidades de paridad por cada 16 o más unidades de datos. Para utilizar el modo RAID 6, la configuración debe contener al menos 20 unidades. Aunque RAID6 puede aumentar la eficiencia de almacenamiento del dispositivo en comparación con DDP, no es recomendable para la mayoría de entornos StorageGRID.



IMPORTANT: Si alguno de los volúmenes ya está configurado o si StorageGRID se instaló anteriormente, al cambiar el modo RAID se quitan y se reemplazan los volúmenes. Se perderán todos los datos de estos volúmenes.

.Pasos
. Con el portátil de servicio, abra un explorador web y acceda al instalador de dispositivos de StorageGRID: +
`*https://_E5700SG_Controller_IP_:8443*`
+
Donde `_E5700SG_Controller_IP_` Es cualquiera de las direcciones IP de la controladora E5700SG.

. Seleccione *Avanzado* > *modo RAID*.
. En la página *Configurar el modo RAID*, seleccione el modo RAID deseado en la lista desplegable modo.
. Haga clic en *Guardar*.


.Información relacionada
http://["Sitio de documentación para sistemas E-Series y EF-Series de NetApp"^]
