---
permalink: expand/gather-required-materials.html 
sidebar: sidebar 
keywords: expand, expansion, planning, storagrid files 
summary: Antes de realizar una operación de expansión, recopile los materiales e instale y configure cualquier hardware y redes nuevos. 
---
= Reúna los materiales necesarios
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de realizar una operación de expansión, recopile los materiales e instale y configure cualquier hardware y redes nuevos.

[cols="1a,2a"]
|===
| Elemento | Notas 


 a| 
Archivo de instalación de StorageGRID
 a| 
Si va a añadir nodos de grid o un sitio nuevo, debe descargar y extraer el archivo de instalación de StorageGRID. Debe utilizar la misma versión que se esté ejecutando actualmente en la cuadrícula.

Para obtener más detalles, consulte las instrucciones de <<download-and-extract-install-files,Descarga y extracción de los archivos de instalación de StorageGRID>>.

*Nota:* no es necesario descargar archivos si va a añadir volúmenes de almacenamiento nuevos a nodos de almacenamiento existentes o a instalar un dispositivo StorageGRID nuevo.



 a| 
Portátil de servicio
 a| 
El portátil de servicio tiene lo siguiente:

* Puerto de red
* Cliente SSH (por ejemplo, PuTTY)
* xref:../admin/web-browser-requirements.adoc[Navegador web compatible]




 a| 
`Passwords.txt` archivo
 a| 
Contiene las contraseñas que se necesitan para acceder a los nodos de grid en la línea de comandos. Incluido en el paquete de recuperación.



 a| 
Clave de acceso de aprovisionamiento
 a| 
La frase de contraseña se crea y documenta cuando se instala el sistema StorageGRID por primera vez. La clave de acceso de aprovisionamiento no está en la `Passwords.txt` archivo.



 a| 
Documentación de StorageGRID
 a| 
* xref:../admin/index.adoc[Administre StorageGRID]
* xref:../release-notes/index.adoc[Notas de la versión]
* Instrucciones de instalación para su plataforma
+
** xref:../rhel/index.adoc[Instale Red Hat Enterprise Linux o CentOS]
** xref:../ubuntu/index.adoc[Instalar Ubuntu o Debian]
** xref:../vmware/index.adoc[Instale VMware]






 a| 
La documentación actual de su plataforma
 a| 
Para conocer las versiones compatibles, consulte https://["Matriz de interoperabilidad"^].

|===


== Descargue y extraiga los archivos de instalación de StorageGRID

.[[descargar-and-extract-install-files]]
Antes de poder añadir nuevos nodos de grid o un sitio nuevo, debe descargar el archivo de instalación de StorageGRID correspondiente y extraer los archivos.

.Acerca de esta tarea
Es necesario realizar operaciones de ampliación con la versión de StorageGRID que se está ejecutando en el grid.

.Pasos
. Vaya a la página de descargas de NetApp para StorageGRID.
+
https://["Descargas de NetApp: StorageGRID"^]

. Seleccione la versión de StorageGRID que se está ejecutando actualmente en la cuadrícula.
. Inicie sesión con el nombre de usuario y la contraseña de su cuenta de NetApp.
. Lea el contrato de licencia para usuario final, seleccione la casilla de verificación y, a continuación, seleccione *Aceptar y continuar*.
. En la columna *instalar StorageGRID* de la página de descarga, seleccione `.tgz` o. `.zip` archivar para su plataforma.
+
La versión que se muestra en el archivo de archivo de instalación debe coincidir con la versión del software que está instalado actualmente.

+
Utilice la `.zip` Archivo si está ejecutando Windows en el portátil de servicio.

+
[cols="1a,2a"]
|===
| Plataforma | Archivo de instalación 


 a| 
Red Hat Enterprise Linux o CentOS
| `StorageGRID-Webscale-_version_-RPM-_uniqueID_.zip`

`StorageGRID-Webscale-_version_-RPM-_uniqueID_.tgz` 


 a| 
Ubuntu o Debian o dispositivos
| `StorageGRID-Webscale-_version_-DEB-_uniqueID_.zip`

`StorageGRID-Webscale-_version_-DEB-_uniqueID_.tgz` 


 a| 
VMware
| `StorageGRID-Webscale-_version_-VMware-_uniqueID_.zip`

`StorageGRID-Webscale-_version_-VMware-_uniqueID_.tgz` 


 a| 
OpenStack/otro hipervisor
 a| 
Para ampliar una puesta en marcha existente en OpenStack, debe implementar una máquina virtual que ejecute una de las distribuciones de Linux admitidas que se indican anteriormente y seguir las instrucciones correspondientes para Linux.

|===
. Descargue y extraiga el archivo de archivo.
. Siga el paso adecuado para que su plataforma elija los archivos que necesite, en función de su plataforma, la topología de cuadrícula planificada y cómo ampliará su sistema StorageGRID.
+
Las rutas enumeradas en el paso de cada plataforma son relativas al directorio de nivel superior instalado por el archivo de archivado.

. Si va a ampliar un sistema Red Hat Enterprise Linux o CentOS, seleccione los archivos adecuados.


[cols="1a,1a"]
|===
| Ruta y nombre de archivo | Descripción 


| ./rpms/README  a| 
Archivo de texto que describe todos los archivos contenidos en el archivo de descarga de StorageGRID.



| ./rpms/NLF000000.txt  a| 
Una licencia gratuita que no proporciona ningún derecho de soporte para el producto.



| ./rpms/StorageGRID-Webscale-Images-_version_-SHA.rpm  a| 
PAQUETE RPM para instalar las imágenes de nodo StorageGRID en sus hosts RHEL o CentOS.



| ./rpms/StorageGRID-Webscale-Service-_version_-SHA.rpm  a| 
PAQUETE RPM para instalar el servicio host StorageGRID en sus hosts RHEL o CentOS.



| Herramienta de secuencia de comandos de la implementación | Descripción 


| ./rpms/configure-storagegrid.py  a| 
Script Python que se utiliza para automatizar la configuración de un sistema StorageGRID.



| ./rpms/configure-sga.py  a| 
Una secuencia de comandos Python que se utiliza para automatizar la configuración de los dispositivos StorageGRID.



| ./rpms/configure-storagegrid.sample.json  a| 
Ejemplo de archivo de configuración para utilizar con `configure-storagegrid.py` guión.



| ./rpms/storagegrid-ssoauth.py  a| 
Ejemplo de secuencia de comandos Python que puede utilizar para iniciar sesión en la API de gestión de grid cuando está activado el inicio de sesión único.



| ./rpms/configure-storagegrid.blank.json  a| 
Un archivo de configuración en blanco para usar con el `configure-storagegrid.py` guión.



| ./rpms/extras/ansible  a| 
Ejemplo de rol de Ansible y libro de estrategia para configurar hosts de RHEL o CentOS para puesta en marcha del contenedor StorageGRID. Puede personalizar el rol o el libro de estrategia según sea necesario.



| ./rpms/extras/esquemas api  a| 
Esquemas de API para StorageGRID.

*Nota*: Antes de realizar una actualización, puede utilizar estos esquemas para confirmar que cualquier código que haya escrito para utilizar las API de administración de StorageGRID será compatible con la nueva versión de StorageGRID si no dispone de un entorno StorageGRID que no sea de producción para la comprobación de compatibilidad de actualizaciones.

|===
. Si va a ampliar un sistema Ubuntu o Debian, seleccione los archivos apropiados.


[cols="1a,1a"]
|===
| Ruta y nombre de archivo | Descripción 


| ./debs/README  a| 
Archivo de texto que describe todos los archivos contenidos en el archivo de descarga de StorageGRID.



| ./debs/NLF000000.txt  a| 
Un archivo de licencia de NetApp que no es de producción y que se puede usar para pruebas e implementaciones conceptuales.



| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
PAQUETE DEB para instalar las imágenes del nodo StorageGRID en hosts de Ubuntu o Debian.



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
Suma de comprobación MD5 para el archivo `/debs/storagegrid-webscale-images-version-SHA.deb`.



| ./debs/storagegrid-webscale-service-version-SHA.deb  a| 
PAQUETE DEB para instalar el servicio de host de StorageGRID en hosts de Ubuntu o Debian.



| Herramienta de secuencia de comandos de la implementación | Descripción 


| ./debs/configure-storagegrid.py  a| 
Script Python que se utiliza para automatizar la configuración de un sistema StorageGRID.



| ./debs/configure-sga.py  a| 
Una secuencia de comandos Python que se utiliza para automatizar la configuración de los dispositivos StorageGRID.



| ./debs/storagegrid-ssoauth.py  a| 
Ejemplo de secuencia de comandos Python que puede utilizar para iniciar sesión en la API de gestión de grid cuando está activado el inicio de sesión único.



| ./debs/configure-storagegrid.sample.json  a| 
Ejemplo de archivo de configuración para utilizar con `configure-storagegrid.py` guión.



| ./debs/configure-storagegrid.blank.json  a| 
Un archivo de configuración en blanco para usar con el `configure-storagegrid.py` guión.



| ./débitos/extras/ansible  a| 
Ejemplo de rol de Ansible y libro de aplicaciones para configurar hosts Ubuntu o Debian para la implementación del contenedor StorageGRID. Puede personalizar el rol o el libro de estrategia según sea necesario.



| ./debs/extras/esquemas api  a| 
Esquemas de API para StorageGRID.

*Nota*: Antes de realizar una actualización, puede utilizar estos esquemas para confirmar que cualquier código que haya escrito para utilizar las API de administración de StorageGRID será compatible con la nueva versión de StorageGRID si no dispone de un entorno StorageGRID que no sea de producción para la comprobación de compatibilidad de actualizaciones.

|===
. Si va a ampliar un sistema VMware, seleccione los archivos adecuados.


[cols="1a,1a"]
|===
| Ruta y nombre de archivo | Descripción 


| ./vsphere/README  a| 
Archivo de texto que describe todos los archivos contenidos en el archivo de descarga de StorageGRID.



| ./vsphere/NLF000000.txt  a| 
Una licencia gratuita que no proporciona ningún derecho de soporte para el producto.



| ./vsphere/NetApp-SG-version-SHA.vmdk  a| 
El archivo de disco de máquina virtual que se usa como plantilla para crear máquinas virtuales del nodo de grid.



| ./vsphere/vsphere-primary-admin.ovf ./vsphere/vsphere-primary-admin.mf  a| 
El archivo de plantilla Abrir formato de virtualización (`.ovf`) y el archivo de manifiesto (`.mf`) Para implementar el nodo de administración principal.



| ./vsphere/vsphere-non-primary-admin.ovf ./vsphere/vsphere-non-primary-admin.mf  a| 
El archivo de plantilla (`.ovf`) y el archivo de manifiesto (`.mf`) Para implementar nodos de administración no primarios.



| ./vsphere/vsphere-archive.ovf ./vsphere/vsphere-archive.mf  a| 
El archivo de plantilla (`.ovf`) y el archivo de manifiesto (`.mf`) Para implementar nodos de archivado.



| ./vsphere/vsphere-gateway.ovf ./vsphere/vsphere-gateway.mf  a| 
El archivo de plantilla (`.ovf`) y el archivo de manifiesto (`.mf`) Para implementar nodos de puerta de enlace.



| ./vsphere/vsphere-storage.ovf ./vsphere/vsphere-storage.mf  a| 
El archivo de plantilla (`.ovf`) y el archivo de manifiesto (`.mf`) Para implementar nodos de almacenamiento basados en máquinas virtuales.



| Herramienta de secuencia de comandos de la implementación | Descripción 


| ./vsphere/deploy-vsphere-ovftool.sh  a| 
Una secuencia de comandos de shell Bash que se utiliza para automatizar la implementación de nodos de cuadrícula virtual.



| ./vsphere/deploy-vsphere-ovftool-sample.ini  a| 
Ejemplo de archivo de configuración para utilizar con `deploy-vsphere-ovftool.sh` guión.



| ./vsphere/configure-storagegrid.py  a| 
Script Python que se utiliza para automatizar la configuración de un sistema StorageGRID.



| ./vsphere/configure-sga.py  a| 
Una secuencia de comandos Python que se utiliza para automatizar la configuración de los dispositivos StorageGRID.



| ./vsphere/storagegrid-ssoauth.py  a| 
Ejemplo de secuencia de comandos Python que puede utilizar para iniciar sesión en la API de gestión de grid cuando está activado el inicio de sesión único.



| ./vsphere/configure-storagegrid.sample.json  a| 
Ejemplo de archivo de configuración para utilizar con `configure-storagegrid.py` guión.



| ./vsphere/configure-storagegrid.blank.json  a| 
Un archivo de configuración en blanco para usar con el `configure-storagegrid.py` guión.



| ./vsphere/extras/esquemas api  a| 
Esquemas de API para StorageGRID.

*Nota*: Antes de realizar una actualización, puede utilizar estos esquemas para confirmar que cualquier código que haya escrito para utilizar las API de administración de StorageGRID será compatible con la nueva versión de StorageGRID si no dispone de un entorno StorageGRID que no sea de producción para la comprobación de compatibilidad de actualizaciones.

|===
. Si va a ampliar un sistema basado en dispositivos StorageGRID, seleccione los archivos adecuados.


[cols="1a,1a"]
|===
| Ruta y nombre de archivo | Descripción 


| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
DEB el paquete para instalar las imágenes de nodo StorageGRID en sus dispositivos.



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
Suma de comprobación del paquete DE instalación DE DEB utilizado por el instalador de dispositivos de StorageGRID para validar que el paquete está intacto tras la carga.

|===

NOTE: Para la instalación del dispositivo, estos archivos sólo son necesarios si necesita evitar el tráfico de red. El dispositivo puede descargar los archivos necesarios del nodo de administración principal.



== Verifique el hardware y las redes

Antes de iniciar la ampliación del sistema StorageGRID, asegúrese de lo siguiente:

* Se ha instalado y configurado el hardware necesario para admitir los nuevos nodos de grid o un sitio nuevo.
* Todos los nodos nuevos tienen rutas de comunicación bidireccionales con todos los nodos nuevos y existentes (un requisito para la red de grid).
* El nodo de administración principal se puede comunicar con todos los servidores de expansión que tienen la intención de alojar el sistema StorageGRID.
* Si alguno de los nodos nuevos tiene una dirección IP de red de cuadrícula en una subred que no se ha utilizado anteriormente, ya lo ha hecho xref:updating-subnets-for-grid-network.adoc[se añadió la nueva subred] A la lista subred de red de cuadrícula. De lo contrario, tendrá que cancelar la expansión, agregar la nueva subred e iniciar el procedimiento de nuevo.
* No está utilizando la traducción de direcciones de red (NAT) en la red de cuadrícula entre nodos de cuadrícula o entre sitios StorageGRID. Cuando utilice direcciones IPv4 privadas para la red de cuadrícula, esas direcciones deben poder enrudarse directamente desde cada nodo de cuadrícula de cada sitio. Sólo se admite el uso de NAT para tender un puente entre la red Grid a través de un segmento de red pública si se utiliza una aplicación de túnel que sea transparente para todos los nodos de la cuadrícula, lo que significa que los nodos de la cuadrícula no necesitan conocimientos de direcciones IP públicas.
+
Esta restricción NAT es específica de los nodos de cuadrícula y de la red de cuadrícula. Según sea necesario, puede utilizar NAT entre clientes externos y nodos de cuadrícula, por ejemplo, para proporcionar una dirección IP pública para un nodo de puerta de enlace.


