---
permalink: expand/rebalancing-erasure-coded-data-after-adding-storage-nodes.html 
sidebar: sidebar 
keywords: erasure coding, EC, rebalancing, site rebalance procedure 
summary: En algunos casos, es posible que deba reequilibrar los datos de código de borrado al añadir nuevos nodos de almacenamiento. 
---
= Reequilibre los datos con código de borrado tras añadir nodos de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En algunos casos, es posible que deba reequilibrar los datos de código de borrado al añadir nuevos nodos de almacenamiento.

.Lo que necesitará
* Completó los pasos de ampliación para añadir los nuevos nodos de almacenamiento.
* Ha revisado el xref:considerations-for-rebalancing-erasure-coded-data.adoc[consideraciones que tener en cuenta al reequilibrar los datos codificados a borrado].
+

IMPORTANT: Realice este procedimiento sólo si se ha activado la alerta *almacenamiento de objetos bajo* para uno o más nodos de almacenamiento de un sitio y no pudo agregar el número recomendado de nuevos nodos de almacenamiento.

* Usted entiende que los datos de objetos replicados no se moverán con este procedimiento y que el procedimiento de reequilibrio de EC no tenga en cuenta el uso de datos replicados en cada nodo de almacenamiento al determinar dónde se deben mover datos codificados con borrado.
* Usted tiene la `Passwords.txt` archivo.


.Acerca de esta tarea
Cuando se ejecuta el procedimiento de reequilibrio de EC, el rendimiento de las operaciones de ILM y las operaciones del cliente S3 y Swift probablemente se verán afectadas. Por este motivo, solo debe realizar este procedimiento en casos limitados.


NOTE: El procedimiento de reequilibrio CE se reserva temporalmente una gran cantidad de almacenamiento. Es posible que se activen las alertas de almacenamiento, pero se resolverán cuando se complete el reequilibrio. Si no hay suficiente almacenamiento para la reserva, se producirá un error en el procedimiento de reequilibrio de la CE. Las reservas de almacenamiento se liberan cuando finaliza el procedimiento de reequilibrio de EC, tanto si el procedimiento ha fallado como si ha sido correcto.

[NOTE]
====
Las operaciones de API de S3 y Swift para cargar objetos (o partes de objetos) pueden fallar durante el procedimiento de reequilibrio de EC si se necesitan más de 24 horas para completarse. Se producirá un error en las operaciones DE COLOCACIÓN de larga duración si la regla de ILM aplicable utiliza una ubicación estricta o equilibrada en el procesamiento. Se informará del siguiente error:

`500 Internal Server Error`

====
.Pasos
. [[Review_Object_Storage]]Revise los detalles del almacenamiento de objetos actual para el sitio que planea reequilibrar.
+
.. Seleccione *NODES*.
.. Seleccione el primer nodo de almacenamiento del sitio.
.. Seleccione la ficha *almacenamiento*.
.. Pase el cursor sobre el gráfico almacenamiento usado - datos de objetos para ver la cantidad actual de datos replicados y los datos codificados para borrado en el nodo de almacenamiento.
.. Repita estos pasos para ver los otros nodos de almacenamiento del sitio.


. Inicie sesión en el nodo de administración principal:
+
.. Introduzca el siguiente comando: `ssh admin@_primary_Admin_Node_IP_`
.. Introduzca la contraseña que aparece en `Passwords.txt` archivo.
.. Introduzca el siguiente comando para cambiar a la raíz: `su -`
.. Introduzca la contraseña que aparece en `Passwords.txt` archivo.
+
Cuando ha iniciado sesión como root, el símbolo del sistema cambia de `$` para `#`.



. Introduzca el siguiente comando:
+
`rebalance-data start --site "_site-name_"`

+
Para `"_site-name_"`, Especifique el primer sitio en el que ha agregado nuevos nodos o nodos de almacenamiento. Encierre `site-name` entre comillas.

+
Se inicia el procedimiento de reequilibrio de EC y se devuelve un ID de trabajo.

. Copie el ID del trabajo.
. Supervisar el estado del procedimiento de reequilibrio de EC.
+
** Para ver el estado de un único procedimiento de reequilibrio de EC:
+
`rebalance-data status --job-id _job-id_`

+
Para `_job-id_`, Especifique el código que se devolvió al iniciar el procedimiento.

** Para ver el estado del procedimiento de reequilibrio de EC actual y de cualquier procedimiento completado anteriormente:
+
`rebalance-data status`

+
[NOTE]
====
Para obtener ayuda sobre el comando de reequilibrio de datos:

`rebalance-data --help`

====
** Para ver el tiempo estimado hasta la finalización y el porcentaje de finalización del trabajo actual, seleccione *SUPPORT* > *Tools* > *Metrics*. A continuación, seleccione *EC Overview* en la sección Grafana. Consulte los paneles *tiempo estimado de trabajo de Grid EC hasta finalización* y *Porcentaje de trabajo de Grid EC completado*.


. Realice pasos adicionales según el estado devuelto:
+
** Si el estado es `In progress`, La operación de reequilibrio de EC todavía se está ejecutando. Deberá supervisar el procedimiento de forma periódica hasta que finalice.
** Si el estado es `Failure`, realice la <<rebalance_fail,pasos de fallo>>.
** Si el estado es `Success`, realice la <<rebalance_succeed,paso del éxito>>.


. Si el procedimiento de reequilibrio de EC genera demasiada carga (por ejemplo, se ven afectadas las operaciones de ingesta), detenga el procedimiento.
+
`rebalance-data pause --job-id _job-id_`

. Si necesita finalizar el procedimiento de reequilibrio de EC (por ejemplo, para poder realizar una actualización del software StorageGRID), introduzca lo siguiente:
+
`rebalance-data terminate --job-id _job-id_`

+

NOTE: Al finalizar un procedimiento de reequilibrio de EC, los fragmentos de datos que ya se hayan movido permanecen en la nueva ubicación. Los datos no se mueven de nuevo a la ubicación original.

. [[reequilibrar_fail]]Si el estado del procedimiento de reequilibrio de EC es `Failure`, siga estos pasos:
+
.. Confirmar que todos los nodos de almacenamiento del sitio están conectados a la cuadrícula.
.. Compruebe y resuelva las alertas que puedan afectar a estos nodos de almacenamiento.
+
Para obtener información sobre alertas específicas, consulte las instrucciones de supervisión y solución de problemas.

.. Reinicie el procedimiento de reequilibrio de EC: +
`rebalance-data start –-job-id _job-id_`
.. Si el estado del procedimiento de reequilibrio de la CE es todavía `Failure`, póngase en contacto con el soporte técnico.


. [[reequilibrar_éxito]]Si el estado del procedimiento de reequilibrio de EC es `Success`, opcionalmente <<review_object_storage,revisar el almacenamiento de objetos>> para ver los detalles actualizados del sitio.
+
Los datos codificados con borrado ahora deberían tener más equilibrio entre los nodos de almacenamiento ubicados en las instalaciones.

. Si utiliza la codificación de borrado en más de una instalación, ejecute este procedimiento para el resto de las ubicaciones afectadas.

