---
permalink: expand/verifying-storage-node-is-active.html 
sidebar: sidebar 
keywords: expand, expansion, add storage nodes, verify node is active 
summary: Después de que se complete una operación de ampliación que añade nuevos nodos de almacenamiento, el sistema StorageGRID deberá empezar automáticamente a usar los nuevos nodos de almacenamiento. Debe utilizar el sistema StorageGRID para comprobar que el nodo de almacenamiento nuevo esté activo. 
---
= Compruebe que el nodo de almacenamiento esté activo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de que se complete una operación de ampliación que añade nuevos nodos de almacenamiento, el sistema StorageGRID deberá empezar automáticamente a usar los nuevos nodos de almacenamiento. Debe utilizar el sistema StorageGRID para comprobar que el nodo de almacenamiento nuevo esté activo.

.Pasos
. Inicie sesión en Grid Manager mediante una xref:../admin/web-browser-requirements.adoc[navegador web compatible].
. Seleccione *NODES* > *_Expansion Storage Node_* > *Storage*.
. Pase el cursor sobre el gráfico *almacenamiento usado - datos de objeto* para ver el valor de *utilizado*, que es la cantidad de espacio útil total que se ha utilizado para los datos de objeto.
. Compruebe que el valor de *utilizado* aumenta a medida que mueve el cursor a la derecha del gráfico.

