---
permalink: ilm/advantages-disadvantages-of-ingest-options.html 
sidebar: sidebar 
keywords: ingest options, balance ingest, strict ingest, dual commit ingest 
summary: 'Comprender las ventajas y las desventajas de cada una de las tres opciones de protección de datos en el procesamiento \(balanceado, estricto o compromiso doble\) puede ayudarle a decidir cuál seleccionar para una regla de ILM.' 
---
= Ventajas, inconvenientes y limitaciones de las opciones de protección de datos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Comprender las ventajas y las desventajas de cada una de las tres opciones de protección de datos en el procesamiento (confirmación equilibrada, estricta o doble) puede ayudarle a decidir cuál seleccionar para una regla de ILM.



== Ventajas de las opciones equilibradas y estrictas

En comparación con el registro doble, que crea copias provisionales durante la ingesta, las dos opciones de colocación sincrónica pueden proporcionar las siguientes ventajas:

* *Mejor seguridad de datos*: Los datos de objeto están protegidos inmediatamente como se especifica en las instrucciones de colocación de la regla ILM, que se pueden configurar para proteger contra una amplia variedad de condiciones de fallo, incluyendo la falla de más de una ubicación de almacenamiento. La confirmación doble solo puede protegerse contra la pérdida de una única copia local.
* *Funcionamiento de red más eficiente*: Cada objeto se procesa una sola vez, ya que se ingiere. Dado que el sistema StorageGRID no necesita realizar un seguimiento o eliminar copias provisionales, hay menos carga de procesamiento y se consume menos espacio de la base de datos.
* *(equilibrado) recomendado*: La opción equilibrada proporciona una eficiencia óptima de ILM. Se recomienda utilizar la opción de equilibrio a menos que se requiera un comportamiento estricto de la ingesta o que la cuadrícula cumpla todos los criterios para la confirmación doble.
* *(estricta) certeza acerca de las ubicaciones de objetos*: La opción estricta garantiza que los objetos se almacenen inmediatamente de acuerdo con las instrucciones de colocación en la regla ILM.




== Desventajas de las opciones equilibradas y estrictas

En comparación con la confirmación doble, las opciones equilibradas y estrictas tienen algunas desventajas:

* *Procesamiento de clientes más largos*: Las latencias de procesamiento de clientes pueden ser más largas. Al utilizar las opciones equilibradas y estrictas, no se devuelve al cliente un mensaje «'ingesta correcta» hasta que se crean y almacenan todos los fragmentos codificados con borrado o copias replicadas. Sin embargo, lo más probable es que los datos de objetos lleguen a su ubicación final mucho más rápido.
* *(estricta) tasas más altas de error de procesamiento*: Con la opción estricta, la ingesta falla cuando StorageGRID no puede realizar de inmediato todas las copias especificadas en la regla ILM. Es posible que observe tasas elevadas de error de procesamiento si una ubicación de almacenamiento necesaria está temporalmente sin conexión o si los problemas de red provocan retrasos en la copia de objetos entre sitios.
* * (Estricta) las ubicaciones de carga de varias partes de S3 pueden no ser las esperadas en algunas circunstancias*: Con estricta, se espera que los objetos se coloquen como se describe en la regla ILM o que falle el procesamiento. Sin embargo, con la carga de varias partes de S3, la gestión del ciclo de vida de la información se evalúa para cada parte del objeto según se ingiere y el objeto como un todo cuando se completa la carga de varias partes. En las siguientes circunstancias, esto podría dar lugar a colocaciones que son diferentes de lo esperado:
+
** *Si ILM cambia mientras una carga multiparte de S3 está en curso*: Debido a que cada pieza se coloca según la regla que está activa cuando se ingiere la pieza, es posible que algunas partes del objeto no cumplan los requisitos actuales de ILM cuando se completa la carga de varias partes. En estos casos, la ingesta del objeto no falla. En su lugar, cualquier pieza que no se haya colocado correctamente se coloca en la cola de repetición de la evaluación de ILM y se mueve a la ubicación correcta más adelante.
** *Cuando las reglas de ILM filtran el tamaño*: Al evaluar ILM para una pieza, StorageGRID filtra el tamaño de la pieza, no el tamaño del objeto. Esto significa que las partes de un objeto se pueden almacenar en ubicaciones que no cumplen los requisitos de ILM para el objeto como un todo. Por ejemplo, si una regla especifica que todos los objetos de 10 GB o más se almacenan en DC1 mientras que todos los objetos más pequeños se almacenan en DC2, al ingerir cada parte de 1 GB de una carga multiparte de 10 partes se almacena en DC2. Cuando se evalúa ILM para el objeto, todas las partes del objeto se mueven a DC1.


* *(estricta) la ingesta no falla cuando las etiquetas de objeto o los metadatos se actualizan y las colocaciones recientemente requeridas no se pueden hacer*: Con estricto, se espera que los objetos se coloquen como se describe en la regla ILM o que falle el procesamiento. Sin embargo, cuando se actualizan metadatos o etiquetas de un objeto que ya está almacenado en la cuadrícula, el objeto no se vuelve a procesar. Esto significa que los cambios en la ubicación de objetos que se activan mediante la actualización no se realizan inmediatamente. Los cambios de colocación se realizan cuando la ILM se vuelve a evaluar por los procesos normales de ILM en segundo plano. Si no se pueden realizar cambios de colocación necesarios (por ejemplo, debido a que una ubicación recientemente requerida no está disponible), el objeto actualizado conserva su ubicación actual hasta que los cambios de colocación sean posibles.




== Limitaciones en la colocación de objetos con las opciones equilibradas o estrictas

Las opciones equilibradas o estrictas no se pueden utilizar para las reglas de ILM que tengan cualquiera de las siguientes instrucciones de colocación:

* Ubicación en un pool de almacenamiento en cloud desde el día 0.
* Ubicación en un nodo de archivado en el día 0.
* Ubicaciones en un pool de almacenamiento en cloud o un nodo de archivado cuando la regla tiene un tiempo de creación definido por el usuario como su tiempo de referencia.


Estas restricciones existen porque StorageGRID no puede hacer copias de forma síncrona en un pool de almacenamiento en cloud o un nodo de archivado y un tiempo de creación definido por el usuario puede resolver este problema en el presente.



== Cómo interactúan las reglas de ILM y los controles de coherencia para afectar a la protección de los datos

Tanto la regla de ILM como la elección del control de coherencia afectan a la forma en que se protegen los objetos. Estos ajustes pueden interactuar.

Por ejemplo, el comportamiento de ingesta seleccionado para una regla de ILM afecta la colocación inicial de las copias de objetos, mientras que el control de consistencia utilizado cuando se almacena un objeto afecta la colocación inicial de los metadatos de objetos. Dado que StorageGRID requiere acceso tanto a los metadatos de un objeto como a sus datos para cumplir con las solicitudes de los clientes, seleccionar los niveles de protección correspondientes para el nivel de coherencia y el comportamiento de ingesta puede proporcionar una mejor protección de datos inicial y respuestas más predecibles del sistema.

A continuación encontrará un breve resumen de los controles de consistencia disponibles en StorageGRID:

* *All*: Todos los nodos reciben metadatos de objeto inmediatamente o la solicitud falla.
* *Strong-global*: Los metadatos de objetos se distribuyen inmediatamente a todos los sitios. Garantiza la coherencia de lectura tras escritura para todas las solicitudes del cliente en todos los sitios.
* *Strong-site*: Los metadatos del objeto se distribuyen inmediatamente a otros nodos en el sitio. Garantiza la coherencia de lectura tras escritura para todas las solicitudes del cliente dentro de un sitio.
* *Read-after-new-write*: Proporciona consistencia de lectura-after-write para nuevos objetos y eventual consistencia para actualizaciones de objetos. Ofrece garantías de alta disponibilidad y protección de datos.
* *Disponible* (eventual consistencia para las operaciones DE LA CABEZA): Se comporta igual que el nivel de consistencia "entre-después-nueva-escritura", pero sólo proporciona consistencia eventual para las operaciones DE LA CABEZA.



NOTE: Antes de seleccionar un nivel de coherencia, lea la descripción completa de los controles de coherencia en las instrucciones para xref:../s3/consistency-controls.adoc[S3] o. xref:../swift/storagegrid-swift-rest-api-operations.adoc[Swift] aplicaciones cliente. Debe comprender los beneficios y las limitaciones antes de cambiar el valor predeterminado.



== Ejemplo de cómo puede interactuar el control de consistencia y la regla de ILM

Suponga que tiene una cuadrícula de dos sitios con la siguiente regla de ILM y la siguiente configuración de nivel de coherencia:

* *Norma ILM*: Cree dos copias de objetos, una en el sitio local y otra en un sitio remoto. Se ha seleccionado el comportamiento de procesamiento estricto.
* *Nivel de coherencia*: "Strong-global" (los metadatos de objetos se distribuyen inmediatamente a todos los sitios).


Cuando un cliente almacena un objeto en el grid, StorageGRID realiza copias de objetos y distribuye los metadatos en ambos sitios antes de devolver el éxito al cliente.

El objeto está completamente protegido contra la pérdida en el momento del mensaje de procesamiento correcto. Por ejemplo, si el sitio local se pierde poco después del procesamiento, seguirán existiendo copias de los datos del objeto y los metadatos del objeto en el sitio remoto. El objeto se puede recuperar completamente.

Si en su lugar usa la misma regla de ILM y el nivel de consistencia de «otrong-site», es posible que el cliente reciba un mensaje de éxito después de replicar los datos del objeto en el sitio remoto, pero antes de que los metadatos del objeto se distribuyan allí. En este caso, el nivel de protección de los metadatos de objetos no coincide con el nivel de protección de los datos de objetos. Si el sitio local se pierde poco después del procesamiento, se pierden los metadatos del objeto. No se puede recuperar el objeto.

La interrelación entre los niveles de coherencia y las reglas del ILM puede ser compleja. Póngase en contacto con NetApp si necesita ayuda.

.Información relacionada
* xref:example-5-ilm-rules-and-policy-for-strict-ingest-behavior.adoc[Ejemplo 5: Reglas de ILM y política para el comportamiento de consumo estricto]

