---
permalink: ilm/creating-ilm-policy.html 
sidebar: sidebar 
keywords: create ILM policy, information lifecycle policy considerations 
summary: Al crear una política de ILM, para comenzar, debe seleccionar y organizar las reglas de ILM. A continuación, se comprueba el comportamiento de la directiva propuesta simulándola de objetos ingeridos previamente. Cuando esté satisfecho de que la directiva propuesta funcione según lo previsto, puede activarla para crear la directiva activa. 
---
= Cree una política de ILM: Descripción general
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al crear una política de ILM, para comenzar, debe seleccionar y organizar las reglas de ILM. A continuación, se comprueba el comportamiento de la directiva propuesta simulándola de objetos ingeridos previamente. Cuando esté satisfecho de que la directiva propuesta funcione según lo previsto, puede activarla para crear la directiva activa.


CAUTION: Una política de ILM que se configuró incorrectamente puede provocar la pérdida de datos irrecuperable. Antes de activar una política de ILM, revise con detenimiento la política de ILM y sus reglas de ILM, y simule la política de ILM. Confirme siempre que la política de gestión del ciclo de vida de la información funcionará como se pretende.



== Consideraciones que tener en cuenta para crear una política de ILM

* Utilice la política integrada del sistema, la directiva de copias base 2, sólo en sistemas de prueba. La regla hacer 2 copias de esta política utiliza el pool de almacenamiento todos los nodos de almacenamiento, que contiene todos los sitios. Si su sistema StorageGRID tiene más de un sitio, es posible que se coloquen dos copias de un objeto en el mismo sitio.
* Al diseñar una nueva política, tenga en cuenta todos los diferentes tipos de objetos que se podrían procesar en el grid. Asegúrese de que la política incluye reglas para coincidir y colocar estos objetos según sea necesario.
* Mantenga la política de ILM de la forma más sencilla posible. Esto evita situaciones potencialmente peligrosas en las que los datos de objetos no se protegen como se deben realizar cambios en el sistema StorageGRID a lo largo del tiempo.
* Asegúrese de que las reglas de la política están en el orden correcto. Cuando se activa la directiva, las reglas del orden indicado evalúan los objetos nuevos y existentes, empezando por la parte superior. Por ejemplo, si la primera regla de una política coincide con un objeto, dicha regla no será evaluada por ninguna otra regla.
* La última regla de todas las políticas de ILM es la regla predeterminada de ILM, que no puede usar ningún filtro. Si un objeto no ha sido coincidente con otra regla, la regla predeterminada controla dónde se coloca ese objeto y durante cuánto tiempo se retiene.
* Antes de activar una nueva política, revise los cambios que realice la política en la ubicación de objetos existentes. El cambio de la ubicación de un objeto existente podría dar lugar a problemas temporales de recursos cuando se evalúan e implementan las nuevas colocaciones.

