---
permalink: ilm/editing-storage-pool.html 
sidebar: sidebar 
keywords: edit storage pool 
summary: Es posible editar un pool de almacenamiento para cambiar su nombre o para actualizar los sitios y las calificaciones de almacenamiento. 
---
= Editar pool de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible editar un pool de almacenamiento para cambiar su nombre o para actualizar los sitios y las calificaciones de almacenamiento.

.Lo que necesitará
* Ha iniciado sesión en Grid Manager mediante un xref:../admin/web-browser-requirements.adoc[navegador web compatible].
* Tiene permisos de acceso específicos.
* Revisó las directrices para crear pools de almacenamiento.
* Si prevé editar un pool de almacenamiento utilizado por una regla en la política de ILM activa, habrá pensado en cómo afectarán los cambios a la ubicación de los datos de los objetos.


.Acerca de esta tarea
Si va a añadir un nuevo nivel de almacenamiento a un pool de almacenamiento que utilice la normativa de gestión del ciclo de vida de la información activa, tenga en cuenta que los nodos de almacenamiento del nuevo nivel no se utilizarán automáticamente. Para forzar a StorageGRID a usar un nuevo nivel de almacenamiento, debe activar una nueva política de ILM después de guardar el pool de almacenamiento editado.

.Pasos
. Seleccione *ILM* > *agrupaciones de almacenamiento*.
+
Aparece la página Storage Pools.

. Seleccione el botón de opción del pool de almacenamiento que desea editar.
+
El pool de almacenamiento todos los nodos del almacenamiento no se puede editar.

. Seleccione *Editar*.
. Según sea necesario, cambie el nombre del pool de almacenamiento.
. Según sea necesario, seleccione otros sitios y grados de almacenamiento.
+

NOTE: No podrá cambiar el sitio o el grado de almacenamiento si el pool de almacenamiento se utiliza en un perfil de código de borrado y el cambio provocaría que el esquema de codificación de borrado no sea válido. Por ejemplo, si un pool de almacenamiento utilizado en un perfil de código de borrado incluye actualmente un grado de almacenamiento con un solo sitio, se le impide utilizar un grado de almacenamiento con dos sitios, ya que el cambio haría que el esquema de código de borrado no sea válido.

. Seleccione *Guardar*.


.Después de terminar
Si agregó un nuevo nivel de almacenamiento a un pool de almacenamiento usado en la política de ILM activa, active una nueva política de ILM para forzar a StorageGRID a usar el nuevo nivel de almacenamiento. Por ejemplo, Clone la política de ILM existente y luego active el clon.
