---
permalink: ilm/what-storage-pool-is.html 
sidebar: sidebar 
keywords: what is a storage pool 
summary: Un pool de almacenamiento es una agrupación lógica de nodos de almacenamiento o nodos de archivado. Los pools de almacenamiento se configuran para determinar dónde el sistema StorageGRID almacena los datos de objetos y el tipo de almacenamiento utilizado. 
---
= Qué es un pool de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un pool de almacenamiento es una agrupación lógica de nodos de almacenamiento o nodos de archivado. Los pools de almacenamiento se configuran para determinar dónde el sistema StorageGRID almacena los datos de objetos y el tipo de almacenamiento utilizado.

Los pools de almacenamiento tienen dos atributos:

* *Grado de almacenamiento*: Para nodos de almacenamiento, el rendimiento relativo del almacenamiento de respaldo.
* *Sitio*: El centro de datos donde se almacenarán los objetos.


Las reglas de ILM permiten utilizar los pools de almacenamiento para determinar dónde se almacenan los datos de objetos. Cuando se configuran las reglas de ILM para la replicación, se deben seleccionar uno o varios pools de almacenamiento que incluyen nodos de almacenamiento o nodos de archivado. Cuando se crean perfiles de código de borrado, se selecciona un pool de almacenamiento que incluye nodos de almacenamiento.
