---
permalink: fabricpool/configuring-dns-for-storagegrid-ip-addresses.html 
sidebar: sidebar 
keywords: fabricPool, DNS, domain name system, FQDN, fully qualified domain name, IP address, VIP 
summary: 'Después de configurar los grupos de alta disponibilidad y los puntos finales del equilibrador de carga, debe asegurarse de que el sistema de nombres de dominio \(DNS\) del sistema ONTAP incluye un registro para asociar el nombre del servidor StorageGRID \(nombre de dominio completo\) a la dirección IP que FabricPool utilizará para realizar conexiones.' 
---
= Configure el servidor DNS para las direcciones IP de StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de configurar los grupos de alta disponibilidad y los extremos de equilibrador de carga, debe asegurarse de que el sistema de nombres de dominio (DNS) del sistema ONTAP incluye un registro para asociar el nombre del servidor StorageGRID (nombre de dominio completo) a la dirección IP que FabricPool utilizará para realizar conexiones.

La dirección IP que introduzca en el registro DNS depende de si se utiliza un grupo de alta disponibilidad de nodos con balanceo de carga:

* Si ha configurado un grupo de alta disponibilidad, FabricPool se conectará a las direcciones IP virtuales de dicho grupo.
* Si no utiliza un grupo de alta disponibilidad, FabricPool puede conectarse al servicio de equilibrado de carga de StorageGRID mediante la dirección IP de cualquier nodo de puerta de enlace o nodo de administración.


También debe asegurarse de que el registro DNS hace referencia a todos los nombres de dominio de extremo requeridos, incluidos los nombres de comodín.
