---
permalink: fabricpool/creating-ha-group-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, high availability group, HA group, create, creating, virtual IP, VIP, preferred master, backup interface 
summary: 'Al configurar StorageGRID para su uso con FabricPool, puede crear opcionalmente uno o varios grupos de alta disponibilidad \(ha\). Un grupo de alta disponibilidad consta de una o varias interfaces de red en los nodos de administración, los nodos de puerta de enlace o ambos.' 
---
= Crear un grupo de alta disponibilidad para FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al configurar StorageGRID para su uso con FabricPool, puede opcionalmente crear uno o varios grupos de alta disponibilidad (ha). Un grupo de alta disponibilidad consta de una o varias interfaces de red en los nodos de administración, los nodos de puerta de enlace o ambos.

.Lo que necesitará
* Ha iniciado sesión en Grid Manager mediante un xref:../admin/web-browser-requirements.adoc[navegador web compatible].
* Tiene el permiso acceso raíz.
* Si planea utilizar una VLAN, ha creado la interfaz VLAN. Consulte xref:../admin/configure-vlan-interfaces.adoc[Configure las interfaces VLAN].


.Acerca de esta tarea
Cada grupo de alta disponibilidad utiliza direcciones IP virtuales (VIP) para proporcionar acceso de alta disponibilidad a los servicios compartidos de los nodos asociados.

Para obtener más detalles sobre esta tarea, consulte xref:../admin/managing-high-availability-groups.adoc[Gestión de grupos de alta disponibilidad].

.Pasos
. Seleccione *CONFIGURACIÓN* > *Red* > *grupos de alta disponibilidad*.
. Seleccione *Crear*.
. Introduzca un nombre único y, opcionalmente, una descripción.
. Seleccione una o varias interfaces para añadirlas a este grupo de alta disponibilidad.
+
Utilice los encabezados de columna para ordenar las filas o introduzca un término de búsqueda para localizar las interfaces más rápidamente.

. Determine la interfaz primaria y cualquier interfaz de backup para este grupo de alta disponibilidad.
+
Arrastre y suelte filas para cambiar los valores de la columna *orden de prioridad*.

+
La primera interfaz de la lista es la interfaz principal. La interfaz Primary es la interfaz activa a menos que se produzca un fallo.

+
Si el grupo ha incluye más de una interfaz y la interfaz activa falla, las direcciones VIP se mueven a la primera interfaz de respaldo en el orden de prioridad. Si falla esa interfaz, las direcciones VIP pasan a la siguiente interfaz de respaldo, etc. Cuando se resuelven los fallos, las direcciones VIP vuelven a la interfaz de mayor prioridad disponible.

. Especifique la subred VIP en notación CIDR&#8212;una dirección IPv4 seguida de una barra diagonal y la longitud de la subred (0-32).
+
La dirección de red no debe tener ningún bit de host configurado. Por ejemplo: `192.16.0.0/22`.

. De manera opcional, si las direcciones IP de ONTAP que se utilizan para acceder a StorageGRID no están en la misma subred que las direcciones VIP de StorageGRID, introduzca la dirección IP de la puerta de enlace local VIP de StorageGRID. La dirección IP de la puerta de enlace local debe estar dentro de la subred VIP.
. Introduzca una o más direcciones IP virtuales para el grupo de alta disponibilidad. Puede añadir hasta 10 direcciones IP. Todos los VIP deben estar dentro de la subred VIP.
+
Debe proporcionar al menos una dirección IPv4. De manera opcional, es posible especificar direcciones IPv4 e IPv6 adicionales.

. Seleccione *Crear grupo ha* y, a continuación, seleccione *Finalizar*.

